### ISSUE TITLE
Upgrade from 0.32.7 to 0.33.2: won't start anymore

### ISSUE THREAD

**Issue by hmeerlo** [kubernetes-sigs/karpenter#1013]
### Description

**Observed Behavior**:
Karpenter fails to start with the following log:
```
panic: fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist.

goroutine 1 [running]:
github.com/samber/lo.must({0x208ec20, 0x40009d7f40}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.39.0/errors.go:53 +0x1dc
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter/pkg/controllers.NewControllers({0x2b83158, 0x4000a70000}, 0x4000d5bf10?, {0x2b86ee0, 0x428ed60}, {0x2b92b60?, 0x4000575e60}, {0x2b56460?, 0x400000c5e8}, 0x40009d9960?, ...)
	github.com/aws/karpenter/pkg/controllers/controllers.go:57 +0x46c
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:56 +0x508
```

**Expected Behavior**:
Normal startup

**Reproduction Steps** (Please include YAML):
Not sure, I just upgrade from 0.32.7 to 0.33.2 using Helm upgrade.

**Versions**:
- Chart Version: 0.33.2
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+orb1
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Ok apparently the instructions for upgrading to 0.32.7 included the interruption queue setting by default

Can you share the settings that you are using when you were installing Karpenter on v0.33.2? There shouldn't have been any changes in how we handle the install with interruption queue. The only change here would be that we silently ignored the setting if you were setting it on an earlier version but didn't notice it, whereas now we are telling you that you set a setting for a queue that doesn't exist and not allowing it to start.

Sounds like you might have been setting `settings.aws.interruptionQueueName` in v0.32.7 but just weren't using it>

**Comment by hmeerlo** [comment]
Yes you are correct. I have been setting settings.aws.interruptionQueueName
in v0.32.7 (because the upgrade instructions contained it), but I wasn't
using it. So I removed the setting and now it works fine.

**Comment by jonathan-innis** [comment]
> but I wasn't
using it. So I removed the setting and now it works fine

Perfect. Yeah, we assume that users are using the interruption queue both in our Getting Started Guide and in our Upgrade Guide. It's hard to handle every configuration that users want to set through the settings, which is why we are trying to fail early now so that you know you should remove the setting.

**Comment by jonathan-innis** [comment]
Out of curiousity, what's the reason that you aren't using the interruption queue?

**Comment by oliverpark999** [comment]
To many people who are exposed to this error,
0.37.0 version
Alternatively, if you are upgrading to the latest version
It is possible that many values have changed.

When using AWS Provider
Do not use settings.aws.
The queue should not use url.
Do not use arn.
Use the interrupt queue as the name.

Our time is precious.
