### ISSUE TITLE
Convert `disrupting via consolidation delete, terminating 1 candidates...` disruption log to use structured log values

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#1026]
### Description

**What problem are you trying to solve?**

It would be nice if our logs that we use in the disruption controller that say `disrupting via consolidation delete, terminating 1 candidates...` or similar could use structured values. We currently produce a templated string. This would be a further improvement of #1025

#### Current Log (example)

```bash
karpenter-69dcf88746-ld26m controller {"level":"INFO","time":"2024-02-15T15:40:51.364Z","logger":"controller.disruption","message":"disrupting via consolidation delete, terminating 1 candidates ip-10-156-106-199.us-east-2.compute.internal/m7i-flex.xlarge/spot","commit":"8fb62bf"}
```

#### Proposed Log (example)

```bash
karpenter-69dcf88746-ld26m controller {"level":"INFO","time":"2024-02-15T15:40:51.364Z","logger":"controller.disruption","method":"consolidation","action":"delete","candidates":"ip-10-156-106-199.us-east-2.compute.internal/m7i-flex.xlarge/spot","candidate-count":"1","pods":"example-pods","pod-count":"1","message":"executing disruption decision","commit":"8fb62bf"}
```

Some ideas for structured values that we could use here:
1. Method
2. Action
3. Candidates (include node name, nodeclaim name, instance type, capacity type)
4. Candidate Count
5. Pods (include namespace/name)
6. Pod Count

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AvineshTripathi** [comment]
Hey I would like work on this issue
