### ISSUE TITLE
Remove Webhooks in Favor of OpenAPI/CEL CRD Validation

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/karpenter#103]
Hi,

I'm trying to understand the benefits which the Karpenter webhooks provide.

Looking at the [validating webhook code](https://github.com/aws/karpenter-core/blob/4e7255c0e5b0037327a93c0b936fae6ea67c30c5/pkg/apis/v1alpha5/provisioner_validation.go) it seems that the same validation could be done via the CRD schema.

The [defaulting webhook](https://github.com/aws/karpenter-core/blob/4e7255c0e5b0037327a93c0b936fae6ea67c30c5/pkg/apis/v1alpha5/provisioner_defaults.go) doesn't seem to do anything at all. In addition, you can add default values to the CRD schema.

**Comment by ellistarn** [comment]
We haven't gone through the exercise of using builtin CRD validation. The defaults are provider specific. See: https://github.com/aws/karpenter/blob/main/pkg/apis/v1alpha5/provisioner.go#L45

**Comment by dudicoco** [comment]
> We haven't gone through the exercise of using builtin CRD validation.

@ellistarn can you please elaborate on that?
It is much easier to add some fields to the CRD schema than writing additional code to validate it.
For example the following [code](https://github.com/aws/karpenter-core/blob/4e7255c0e5b0037327a93c0b936fae6ea67c30c5/pkg/apis/v1alpha5/provisioner_validation.go#L222-L225) could be easily replaced with a `required: ["evictionSoftGracePeriod"]` block within the schema.

I believe the defaulting webhook could also be avoided by adding `default` fields within the CRD schema.

**Comment by ellistarn** [comment]
Interesting ideas. Would you be interested in contributing this?

**Comment by dudicoco** [comment]
@ellistarn sure.
Should I open a PR for the CRDs?

**Comment by ellistarn** [comment]
Sure thing!

**Comment by jonathan-innis** [comment]
Kubernetes supports [CEL for CRD validation](https://kubernetes.io/docs/reference/using-api/cel/). We should investigate this along with the other validations that are supported natively by the Open API specs (like defaults, minimum, maximums, etc.)
