### ISSUE TITLE
Custom Drift Interval

### ISSUE THREAD

**Issue by Robyt96** [kubernetes-sigs/karpenter#1052]
### Description

**What problem are you trying to solve?**
Hi, I would like some clarification on the drift mechanism of Karpenter. From this [post](https://aws.amazon.com/blogs/containers/how-to-upgrade-amazon-eks-worker-nodes-with-karpenter-drift/#:~:text=For%20Kubernetes%20nodes%20provisioned%20with,is%20set%20to%205%20minutes.) and from some tests conducted, I observe that Karpenter has a drift interval of approximately 5 minutes. Here an exctract from the logs:
```
{"level":"INFO","time":"2024-02-29T10:20:20.902Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:25:43.811Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:30:12.311Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:36:25.142Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:40:13.588Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:44:12.187Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:47:40.626Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:51:49.059Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
{"level":"INFO","time":"2024-02-29T10:56:31.900Z","logger":"controller.disruption","message":"disrupting via drift replace, terminating 1 candidates ip-IP.REGION.compute.internal/r5.xlarge/on-demand and replacing with on-demand node from types r5.xlarge","commit":"1072d3b"}
```

Is it currently possible to specify this drift interval with any parameters, or is this something that could be implemented?

**How important is this feature to you?**
Our organization requires us to regularly change the AMIs of the cluster nodes, and the drift feature of Karpenter is very useful in this regard. However, our nodes host Java/Springboot workflows with pods that are sometimes very slow to start, so we would need to wait longer between one drift replacement and another.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Since `kubernetes-sigs/karpenter` isn't aware of provider-specific NodeClass, it doesn't track watch events for these NodeClass. We will soon be able to just watch v1beta1.NodeClaimReference objects. Closing this issue as a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/337
