### ISSUE TITLE
Karpenter Community Alerts

### ISSUE THREAD

**Issue by Bryce-Soghigian** [kubernetes-sigs/karpenter#1058]
### Description

**What problem are you trying to solve?**
As we start to add all of the metrics and monitoring improvements for v1, would be good to align and create a list of recommended alerts that can go along with all of the metrics we expose. Metrics are fine and dandy, but alerts are actionable. It would be good if we as a community can maintain a collection of these alerts to make the metrics we emit useful so anyone adopting karpenter can easily monitor its health alongside with a troubleshooting guide if they are experiencing some issues. 

These alerts and metrics can be featured under a new https://karpenter.sh/docs/observability page of the core website, and referenced for users like [this](https://kubernetes.slack.com/archives/C02SFFZSA2K/p1709309766307659). 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
The current dashboards in AWS are merely a suggested starting point for creating your own dashboards. I envision that creating alerts that fit for all Karpenter users is going to be wrong in most cases. Is this something that can be done on a per-cloud provider basis?

**Comment by Bryce-Soghigian** [comment]
Per cloudprovider might make sense for most of them. (HighBootstrapLatency, create or delete qos etc). I do think there is some room for common alerts like "UnschedulablePodsStuck" or karpenter core driven alerts like "AbnormalClusterSyncLatency".

**Comment by njtran** [comment]
What are you thinking would be good values for these alerts? I can imagine that some users are more tolerant and flexible to the amount of unschedulablePodsStuck than others. I'd rather Karpenter be in charge of producing the metrics that people find useful, and allow people to leverage those however it suits them. Additionally if we drive this on a per-CP basis, you could go ahead and potentially package it with an Azure Karpenter release if you have historical knowledge about what are the best alarms that you want to set for all your users.

**Comment by vponoikoait** [comment]
@Bryce-Soghigian why this got closed? I can see metrics description, but no alerts to them
