### ISSUE TITLE
Change Naming format for Karpenter Nodes.

### ISSUE THREAD

**Issue by amitmantha** [kubernetes-sigs/karpenter#1067]
### Description

do we have a option to change the naming format of Nodes which are spun by karpenter.

**Comment by jmdeal** [comment]
This is going to be dependent on the cloudprovider, do you mind reoppening this in either the [AWS](https://github.com/aws/karpenter-provider-aws) or [Azure](https://github.com/Azure/karpenter-provider-azure) provider?

**Comment by njtran** [comment]
Closing this in favor of @amitmantha cutting it in their cloud provider of choice
