### ISSUE TITLE
Add capacity-type label to karpenter_nodes_created and karpenter_nodes_terminated

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1072]
### Description

**What problem are you trying to solve?**

Add `capacity-type` label to `karpenter_nodes_created` and `karpenter_nodes_terminated`, in order to build a dashboard on this data comparing spot and on-demand nodes being created. Currently added as filter in Grafana dashboard Karpenter Capacity (https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/docs/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json) but not used in the panels.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by youwalther65** [comment]
@tvonhacht-apple I just upgraded my AWS provisioner Helm chart to this version `karpenter-0.36.0` but still `karpenter_nodes_created` and `karpenter_nodes_terminated` doesn't contain an additional label `capacity-type`.
Anything I am missing here - nothing specila regarding this in upgrade guide [here](https://karpenter.sh/docs/upgrading/upgrade-guide/#upgrading-to-0360)
