### ISSUE TITLE
Karpenter causes application downtime

### ISSUE THREAD

**Issue by GaborVarga** [kubernetes-sigs/karpenter#1076]
We started to use Karpenter instead of CAS recently and what we see is that when there is some load, Karpenter kills pods and starts them on newly provisioned nodes but there could be 1-2 mins downtime in the service which is not acceptable. 
What is the best practice to avoid this downtime? E.g. force Karpenter to start a new node, start a new pod there and only after this kill the old pod?

**Comment by edas-smith** [comment]
Would advise using this : https://aws.amazon.com/blogs/containers/eliminate-kubernetes-node-scaling-lag-with-pod-priority-and-over-provisioning/ works absolute wonders as currently Karpenter doesn't have a "native" feature for this.

This way pods will be immediately scheduled on existing nodes as it will kick out the over provisioner ( which will be scheduled on new nodes for example )

**Comment by njtran** [comment]
We pre-spin replacement nodes when disrupting nodes, so the pod should have very minimal downtime. Which types of disruption are you talking about? What version of Karpenter are you on?
