### ISSUE TITLE
kubectl get nodepool needs to return READY

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1113]
### Description

**What problem are you trying to solve?**

If the nodepool configuration is incorrect, the nodepool could be invalid causing it not being able to be create node claims. Getting that information on the get call, helps not needing to describe every nodepool and look at the events or even debugging the ec2nodeclass and making that reference yourself.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by engedaam** [comment]
@tvonhacht-apple are you wanting this as a printcolumn?

**Comment by tvonhacht-apple** [comment]
yes, putting it under status and then have it as a default print column

**Comment by jonathan-innis** [comment]
Yep, this is going to be part of the v1 proposal. You can see this RFC here: https://github.com/kubernetes-sigs/karpenter/pull/1222

**Comment by njtran** [comment]
This should be fixed and solved in v1.  https://github.com/kubernetes-sigs/karpenter/pull/1385 and https://github.com/kubernetes-sigs/karpenter/pull/1401 and https://github.com/kubernetes-sigs/karpenter/pull/1365
