### ISSUE TITLE
kubectl get nodepool -o wide should return if its been disrupted

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1114]
### Description

**What problem are you trying to solve?**

Showing a summary if all node claims associated with the nodepool are up to the latest changes would help to debug if the cluster is currently in a progressing state, versus knowing everything is up to the configuration defined.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
@tvonhacht-apple We currently have an issue open for the v1 laundry list and how the printcolums should look https://github.com/kubernetes-sigs/karpenter/issues/493. Would you be willing to close this issue and post add you comments on that issue?

**Comment by tvonhacht-apple** [comment]
read through it, sounds like that issue covers what we were looking for, thank you
