### ISSUE TITLE
kubectl get nodepool -o wide should return if total number of nodeclaims (similar how deployment shows pods, uptodate etc)

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1115]
### Description

**What problem are you trying to solve?**

Showing a summary of the node claims associated and if they are up to current state or currently in drift state by something like 5/6. Would give an idea if something is happening in the cluster currently.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by engedaam** [comment]
@tvonhacht-apple We currently have an issue open for the v1 laundry list and how the printcolums should look https://github.com/kubernetes-sigs/karpenter/issues/493. Would you be willing to close this issue and post add you comments on that issue?

**Comment by tvonhacht-apple** [comment]
thanks added as comment
