### ISSUE TITLE
kubectl rollout restart nodepools <nodepool:optional> if you update karpenter, a forceful way to rotate all nodes

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1116]
### Description

**What problem are you trying to solve?**

To force rotate a nodepool and its node claims, similar to the capabilities of a deployment. Could help forcing on-demand to go back to spot if available. Update other configurations that are deployed with a new karpenter version for example.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by engedaam** [comment]
@tvonhacht-apple Why can't you expire your nodes by setting expireAfter to 1m? This would begin the termination process for all the `NodeClaims` owned by a `NodePool`

**Comment by njtran** [comment]
This is essentially different to how Karpenter currently thinks of upgrades. We do upgrades declaratively, by noticing nodes that aren't in-spec, and gradually upgrading them when the user says Karpenter can. This would be the opposite, driving upgrade imperatively. Are you using Drift right now? What's not working about this?

**Comment by tvonhacht-apple** [comment]
I might be not leveraging karpenter correctly. When I was making some local changes and deploying my own Karpenter version, I was adding additional labels to NodeClaims for debugging purpose. When I was changing logic in those labels nodeclaims wouldn't drift automatically. But I might be adding the labels at the wrong spot. They are dynamic labels based on what ec2.CreateFleet decided to bring up as the EC2 node. So the labels adding is something that might be after/outside of the regular drift detection?

**Comment by jonathan-innis** [comment]
> When I was changing logic in those labels nodeclaims wouldn't drift automatically

Karpenter won't react to direct updates to the NodeClaim in this way. Karpenter [uses a `karpenter.sh/nodepool-hash` annotation in the NodePool](https://karpenter.sh/docs/concepts/disruption/#drift) and updates this hash as the NodePool changes, the NodeClaim gets this `karpenter.sh/nodepool-hash` when it is first created and then other changes to the NodeClaim aren't watched after the fact. We do this to avoid having to recheck every single field inside of the NodeClaim. This mechanism is very similar to how Deployment manages changes to the pod spec. It's possible to change details of the pod spec and the deployment controller won't restore them back.

**Comment by jonathan-innis** [comment]
> To force rotate a nodepool and its node claims, similar to the capabilities of a deployment

How would you imagine this force rotation would happen? You can forcefully terminate all NodeClaims owned by a NodePool today with `kubectl delete nodepool <nodepool-name>`. The only caveat here is that you need to have another NodePool available for the pods to move over to. This is effectively how you can orcehstrate a blue/green rollout strategy with Karpenter.

How are you thinking you'd like to force this migrtion?
