### ISSUE TITLE
Able to define a Consolidation WhenUnderutilized threshold percentage

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1117]
### Description

**What problem are you trying to solve?**

Some node pools we might have a lot of pods getting rotated, having a smaller percentage for what Underutilized mean, would remove the pending time for pods waiting for new nodes to come up, while still trying to keeping the environment at a certain utilization without just using WhenEmpty. The problem with using WhenEmpty that its not optimal for cost, as some pods maybe never get rotated for a long time, keeping the nodes around that have low utilization.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by Bryce-Soghigian** [comment]
@tvonhacht-apple have you checked out: https://github.com/kubernetes-sigs/karpenter/issues/735#issuecomment-1790110263? There is a discussion for this over there.

**Comment by tvonhacht-apple** [comment]
duplicate of #735
