### ISSUE TITLE
kubectl get node claims -o wide should show living status

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1119]
### Description

**What problem are you trying to solve?**

In order to debug if a nodeclaim will get removed, or currently is getting started, or has expired, it would be great to show that information as part of a `-o wide` command for debugging a cluster.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by engedaam** [comment]
@tvonhacht-apple We currently have an issue open for the v1 laundry list and how the `printcolums` should look https://github.com/kubernetes-sigs/karpenter/issues/493. Would you be willing to close this issue and post add you comments on that issue?

**Comment by njtran** [comment]
How does this realistically look different than #1113?

**Comment by tvonhacht-apple** [comment]
> How does this realistically look different than #1113?

that one is about nodepools, this one is for nodeclaims

**Comment by tvonhacht-apple** [comment]
> @tvonhacht-apple We currently have an issue open for the v1 laundry list and how the `printcolums` should look #493. Would you be willing to close this issue and post add you comments on that issue?

Added to PR, thanks for linking me
