### ISSUE TITLE
SpotToSpotConsolidation requires 15 cheaper instance type options than the current candidate to consolidate, got 1

### ISSUE THREAD

**Issue by 1ms-ms** [kubernetes-sigs/karpenter#1124]
### Description

**Observed Behavior**: karpenter doesnt consolidate due to "SpotToSpotConsolidation requires 15 cheaper instance type options than the current candidate to consolidate, got 1".

**Expected Behavior**: karpenter does consolidate when there is possiblity

**Reproduction Steps** (Please include YAML):
In my cluster I have 2 nodes created by default (karpenter is scheduled here) and 1 node created by karpenter. During change from ON-DEMAND -> SPOT for default nodes, karpenter started creating new nodes (as expected), ending up with 3 nodes in total created by karpenter. Once the change from ON-DEMAND to SPOT has been finished I expected karpenter provisioned nodes to be consolidated and I should reach initial state: 2 nodes created by default + 1 created by karpenter. Karpenter tries to do the right change and consolidate WhenUnderutilized, but fails due to "SpotToSpotConsolidation requires 15 cheaper instance type options than the current candidate to consolidate, got 1". 
I am not sure why this error comes up. Why does it require 15 cheaper nodes? As per [docs](https://karpenter.sh/docs/concepts/disruption/#spot-consolidation) it requires 15 instance types, not 15 **cheaper** instance types.

**Versions**:
- Chart Version: 0.35.1
- Kubernetes Version (`kubectl version`): v1.29.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by 1ms-ms** [comment]
update: after 90 minutes of repeating errors, it finally consolidaten. Any way to ensure its done faster?

**Comment by Bryce-Soghigian** [comment]
Can you share your controller logs and nodepools? And a nodeclaim from the time when it was failing?

**Comment by 1ms-ms** [comment]
Controller logs:
`{"level":"INFO","time":"2024-03-21T08:42:01.683Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"cd02bab","pods":"vault/vault-0","duration":"13.78111ms"}
{"level":"INFO","time":"2024-03-21T10:21:36.612Z","logger":"controller.disruption","message":"disrupting via consolidation delete, terminating 1 nodes (0 pods) ip-10-1-12-169.eu-central-1.compute.internal/t4g.small/spot","commit":"cd02bab","command-id":"425e7e10-74a7-40c6-a4a2-22c842172f90"}`
As you can see, for 90 min there were no logs - it created a new node, after ~5 min it tried to consolidate nodes, but failed with error I mentioned earlier and after ~90 min it simply deleted nodes (as expected)

I am not able to get NodeClaims as nodes are already deleted. NodePool has this requirements:
`Spec:
  Disruption:
    Budgets:
      Nodes:               10%
    Consolidation Policy:  WhenUnderutilized
    Expire After:          Never
  Limits:
    Cpu:  1000
  Template:
    Spec:
      Node Class Ref:
        API Version:  karpenter.k8s.aws/v1beta1
        Kind:         EC2NodeClass
        Name:         karpenter-node-pool-class-management
      Requirements:
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          spot
          on-demand`

**Comment by Bryce-Soghigian** [comment]
ok so just to clarify, we saw consolidation delete not replace. Meaning that the node was unneeded. Consolidation replace will still fail due to not enough instance types. 

Spot to spot consolidation will fail [here](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/disruption/consolidation.go#L265C75-L265C117) the consolidation controller checks to see if we have at least 15 cheaper candidates. 

Seems odd that you have 15 cheaper candidates and would still not see spot on spot consolidation. Knowing which instance types were available on the nodeclaim during this selection and their price would be very helpful for investigation.

**Comment by 1ms-ms** [comment]
@Bryce-Soghigian yes, consolidation delete was expected as karpenter provisioned more nodes than needed during capacity-type change for other nodegroup from on-demand to spot. It worked flawlessly, but later I expected a node "cleanup", meaning that overprovisioned nodes will be deleted. Out of 3 nodes provisioned by karpenter, 2 were not needed at all - there was no need for replacing them, but rather deleting (which eventually happened).

What I dont understand is, why it needed 15 **cheaper** instance types. It would be understandable if replace was needed, not deletion. 

If I remember correctly, karpenter provisioned t4g.small, t3a.small and t2.small, out of which t2.small is still there (which is correct). Is it possible that consolidation delete has been finally triggered due to change in spot pricing?

**Comment by nikmohan123** [comment]
I couldn't reproduce the issue. I see the nodes getting deleted when EMPTY with spot-to-spot consolidation enabled and when we transition from OD -> SPOT. Can you please share the NodePool configuration before and after that triggered the drift and as a result consolidation ? The error message that you see is expected for the "replace" consolidation. I am wondering if it is possible for those nodes to NOT be EMPTY and hence the Karpenter was trying to replace it instead of delete it.

**Comment by 1ms-ms** [comment]
@nikmohan123 There was no change in NodePool configuration. I am using NodeGroup in AWS to provision nodes when I bootstrap EKS. Initially I had 2 OD instances there, but I changed to SPOT. This caused pods migration and as a result provisioning of nodes by karpenter. Nodes were not empty, but ithis shouldnt be a problem - I had similar setup today, when Spot nodes were interrupted and nodes were correctly provisioned and deleted (with log `disrupting via consolidation delete, terminating 1 nodes (8 pods)`). 
From what I see, the error I created ticket with was a bug and have not happened since.

**Comment by nikmohan123** [comment]
Thanks @1ms-ms for the clarification. What instance types did you use to create the NodeGroup for OD and what instance types for SPOT ? I also tried from my end with the above steps that you called out and I still do not have a luck in reproducing the issue. Wondering if this problem is specific to few instance types here.

**Comment by 1ms-ms** [comment]
@nikmohan123 I used t4g.small for both OD and SPOT (I didnt change any settings, but capacity type). I did this change some time ago and beside the issue in the ticket, it did not happen anymore (at least I did not see).

**Comment by nikmohan123** [comment]
I tried multiple times from my side too. Couldn't reproduce the issue. Feel free to re-open this if you see this happening again. Closing the issue. Thanks.

**Comment by teocns** [comment]
Reproducing the same after the applying the following mods:


| Section                     | Previous Value                                                                                                             | New Value                                                                                                                                                                                                                                                                                                         |
|-----------------------------|-----------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `spec.disruption`           | `consolidateAfter: "30s"`<br>`consolidationPolicy: "WhenEmpty"`                                                             | `budgets: - nodes: 50%`<br>`consolidationPolicy: "WhenUnderutilized"`<br>`expireAfter: 720h`                                                                                                                                                                                                                      |
| `spec.limits.cpu`           | `1000`                                                                                                                      | `64`                                                                                                                                                                                                                                                                                                               |
| `spec.template.spec.requirements` | `instance-category values: ["c", "m", "r"]`<br>`instance-cpu values: ["4", "8", "16", "32"]`                                | `instance-category values: ["c", "m", "r", "t"]`<br>`instance-cpu values: ["1", "2", "4", "8", "16", "32"]`                                                                                                                                                                                                        |

**Comment by saireddyb-digite** [comment]
Normal  Unconsolidatable  4m38s (x141 over 38h)  karpenter  SpotToSpotConsolidation requires 15 cheaper instance type options than the current candidate to consolidate, got 13
Facing same issue.

All my nodes got of 2 cores still no consolidation.
