### ISSUE TITLE
 allow retries for special users or all users on tests

### ISSUE THREAD

**Issue by Bryce-Soghigian** [kubernetes-sigs/karpenter#1139]
### Description

**What problem are you trying to solve?**
I tend to run into a fair bit of flake when running the tests. It would be nice to be able to retest so that when I ask for reviews the reviewers can just look and see that the checks are green and passing for everything. This way we waste less of everyones time :) 

Its nice that anyone can run the tests on each commit, but if the tests fail I cannot retry the tests even if I know its failing due to flakey reasons. Sometimes I end up just repushing to run the tests and get them to pass before asking for review which seems like the wrong solution.

Either allowing everyone to retry, or having a role/scoped permissions to allow certain trusted members of the community to re-run tests would be great.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Yeah, this is the whole point of /retest. I'm wondering if there's a way to enable this with GHA. If not, we may have to fully shift to K8s-infra
