### ISSUE TITLE
KWOK provider automatically adds "Spot" to NodeClaim even if no spot nodes are available.

### ISSUE THREAD

**Issue by drmorr0** [kubernetes-sigs/karpenter#1144]
### Description

**Observed Behavior**:

If the nodes in the KWOK cloud provider do not support spot, and a deployment is submitted that must be deployed on a KWOK node, Karpenter failes with 

```
{"level":"ERROR","time":"2024-03-28T18:08:15.986Z","logger":"controller","message":"Reconciler error","commit":"c8eda9b-dirty","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"kwok-default-9cdj2"},"namespace":"","name":"kwok-default-9cdj2","reconcileID":"48d1f171-5204-4677-8b1e-a08c52a6bf67","error":"launching nodeclaim, translating nodeclaim to node, failed to find offering spot/test-zone-c/c-128x-amd64-linux"}
```

This error is coming from [L140 in cloudprovider.go](https://github.com/kubernetes-sigs/karpenter/blob/main/kwok/cloudprovider/cloudprovider.go#L140), where the function assumes that spot nodes are available even though none of the nodes actually support spot.

**Expected Behavior**:

Karpenter should launch an on-demand node to schedule the deployment.

**Reproduction Steps** (Please include YAML):

I've created a [branch](https://github.com/acrlabs/karpenter/tree/drmorr/demonstrate-node-claims-spot-bug) demonstrating the behaviour.

1. Build the karpenter version in the above branch
2. Apply the vanilla KWOK controller following the instructions on [the KWOK installation page](https://kwok.sigs.k8s.io/docs/user/kwok-in-cluster/)
3. From the root of the above branch, run `kubectl apply -f ./repro`
4. Check the logs of the created karpenter pod, and observe that the nginx pod does not get scheduled

**Versions**:
- Kubernetes Version (`kubectl version`): 1.27

**Comment by njtran** [comment]
@drmorr0 this should be fixed now, right?

**Comment by drmorr0** [comment]
yes!
