### ISSUE TITLE
Karpenter isn't able Spin new Nodes. (Incompatible with Nodepool)

### ISSUE THREAD

**Issue by amitmantha** [kubernetes-sigs/karpenter#1162]
### Description

**Observed Behavior**:
Installed Karpenter replacing cluster-autoscaler.
But karpenter isn't able to spin new nodes, facing an error stating :

 "{"level":"ERROR","time":"2024-04-03T06:40:04.552Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"675m\",\"memory\":\"390Mi\",\"pods\":\"6\"}, incompatible requirements, label \"nodegroup\" does not have known values","commit":"17d6c05","pod":"com-dtv-dcp-dpd/beamacctgetprofilems-green-746d677b76-lghl4"}"

**Comment by njtran** [comment]
Can you share your nodepools and your pod specs that you're expecting to be scheduled? 

Can you share the full logs too?

**Comment by jonathan-innis** [comment]
Closing since there isn't enough information here and looks like there's no response back in the issue after a month.
