### ISSUE TITLE
scale up Deployment if PDB doesn't meet the scale down/drain requirements

### ISSUE THREAD

**Issue by bbodenmiller** [kubernetes-sigs/karpenter#1171]
### Description

**What problem are you trying to solve?**

If a Deployment has a PDB in place preventing a voluntary disruption would be great if it could scale up Deployment (assuming HPA set) when needed to drain node. At this time in order to ensure up time not affected by voluntary disruptions Deployment must run with 2 replicas and PDB `minAvailable: 1` (HA requires 3 replicas and PDB `minAvailable: 2`). Implement feature that allows Deployments to run as small as possible while still ensuring up time is not affected by voluntary disruptions (e.g. node expiration).

Related:
- https://github.com/kubernetes/autoscaler/issues/1298
- https://github.com/kubernetes/kubernetes/issues/93476

**How important is this feature to you?**

Important to minimize costs.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Currently we already allow Deployments to run with the minimal amount of replicas that the PDBs would allow. I'm not sure if this is a feature request for Karpenter, as we just rely on the upstream eviction API. I'd recommend that you cut and follow an issue in Kubernetes, as this seems more like a feature for PDBs or even a way to implement your HPA.

**Comment by bbodenmiller** [comment]
@njtran how would you implement as HPA?

**Comment by sam-greenleaf** [comment]
Has anyone found a workaround for this yet?
