### ISSUE TITLE
Allow specifying drift allowance for each node pool

### ISSUE THREAD

**Issue by wkd3475** [kubernetes-sigs/karpenter#1179]
### Description

**What problem are you trying to solve?**
I would like to request the ability to specify whether to allow drift for each node pool. By default, I want to enable drift for all node pools. However, in cases where pod rolling should not occur arbitrarily, I want to prevent any incidents caused by accidental drift. Using a budget might help mitigate this issue, but there could still be cost waste if a node is not removed even when in an empty state.

If we could specify whether to allow disruption due to drift for each node pool, this problem would be resolved. Please consider adding this feature as it would help prevent both potential incidents and unnecessary expenses.

Thank you for your consideration.

**How important is this feature to you?**
This feature would enable more granular control over drift and would be beneficial to many users. I believe that providing this level of control will be a valuable addition to the project.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Karpenter is adding disruption budgets per reason.  This should solve that usecase. Please read through the design and let me know.

- [RFC](https://github.com/kubernetes-sigs/karpenter/pull/936)
- [Implementation](https://github.com/kubernetes-sigs/karpenter/pull/991)

**Comment by nadavbuc** [comment]
Please take also scheduling specifically for drifts
for example:
- I Want consolidation to replace nodes whenever
- I Want to allow Drifts (Specifically on AMI - but generally would suffice) only between 03AM to 08AM (using existing budget schedule options) 
For example - just last night we had hundreds of disruptions due to AMIDrift last night for example, we would like to give it "maintenance windows".

**Comment by Bryce-Soghigian** [comment]
that should work with this approach! Do. you care that the nodes replaced for consolidation get upgraded? Or is it just about not mass rolling all the nodes for AMI Drift?

**Comment by Bryce-Soghigian** [comment]
Im going to close as a dup of https://github.com/kubernetes-sigs/karpenter/issues/924, feel free to reopen if there are other concerns!
