### ISSUE TITLE
Karpenter nodes doesn't join aws load balancer registerd target groups to take load.

### ISSUE THREAD

**Issue by dewstyh** [kubernetes-sigs/karpenter#1203]
### Description

**Observed Behavior**: Karpenter nodes are getting created, but nodes are not able to join ec2 registered target groups in order to take load to pods running on karpenter nodes.
![image-20240423-160712](https://github.com/kubernetes-sigs/karpenter/assets/149725919/69431df6-cadb-41c4-a99d-424a0f6f34a2)

**Expected Behavior**: Karpenter should join registered target groups in order take load on to pods running on it's nodes

**Reproduction Steps** (Please include YAML): deployed karpenter on eks manged node group using terraform module eks and submodule of karpenter with version 20.0.0 and helm chart with version v0.34.0, I have registered target groups for my external and internal application load balancer which redirects requests on to pods running on eks managed node groups and not by karpenter nodes.

**Versions**: Karpenter = v0.34.0, Terraform eks module 20.0.0 and karpenter submodule 20.0.0
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): 1.29

My node pool and node class details
```
resource "kubectl_manifest" "karpenter_node_pool" {
  count     = local.is_test_environment ? 0 : 1
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: default
    spec:
      template:
        spec:
          nodeClassRef:
            name: default
          requirements:
            - key: "kubernetes.io/arch"
              operator: In
              values: ["amd64"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: [t3]
            - key: karpenter.k8s.aws/instance-size
              operator: In
              values: [large]
            - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
              operator: In
              values: ["on-demand"]
      disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: 720h
  YAML

  depends_on = [
    helm_release.karpenter, kubectl_manifest.karpenter_node_class
  ]
}

resource "kubectl_manifest" "karpenter_node_class" {
  count     = local.is_test_environment ? 0 : 1
  yaml_body = <<-EOF
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      amiFamily: AL2
      role: ${module.eks.eks_managed_node_groups["two"].iam_role_name}
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${local.cluster_name}
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${local.cluster_name}
      tags:
        karpenter.sh/discovery: ${local.cluster_name}
  EOF

  depends_on = [
    helm_release.karpenter
  ]
}

module and helm chart

module "karpenter" {
  source                        = "terraform-aws-modules/eks/aws//modules/karpenter"
  version                       = "20.0.0"
  cluster_name                  = module.eks.cluster_name
  irsa_oidc_provider_arn        = module.eks.oidc_provider_arn
  enable_irsa                   = true
  create_access_entry           = false
  create_instance_profile       = true
  create_node_iam_role          = false
  node_iam_role_arn             = module.eks.eks_managed_node_groups["two"].iam_role_arn
  node_iam_role_use_name_prefix = false
  node_iam_role_additional_policies = {
    AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  }
  tags = {
    "karpenter.sh/discovery" = local.cluster_name
  }
}

resource "helm_release" "karpenter" {
  count            = local.is_test_environment ? 0 : 1
  create_namespace = true
  namespace        = "karpenter"
  name             = "karpenter"
  repository       = "oci://public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "v0.34.0"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter.iam_role_arn
  }

  set {
    name  = "dnsPolicy"
    value = "Default"
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/sts-regional-endpoints"
    value = "true"
    type  = "string"
  }

  set {
    name  = "settings.clusterName"
    value = module.eks.cluster_name
  }

  set {
    name  = "settings.clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "settings.interruptionQueue"
    value = module.karpenter.queue_name
  }

  values = [
    <<-EOT
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "karpenter.sh/nodepool"
                operator: "DoesNotExist"
    EOT
  ]

  depends_on = [module.eks.eks_managed_node_groups, module.eks]
}
```
Please let me know what I'm missing or it's a bug.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewstyh** [comment]
kubectl of my targetgroup binding created by alb when i add above mentioned annotation

kubectl describe targetgroupbindings  k8s-stagingi-callisto-224c049c92 -n staging-ibwave - o yaml
Name:         k8s-stagingi-callisto-224c049c92
Namespace:    staging-ibwave
Labels:       ingress.k8s.aws/stack=staging-ingress-group
Annotations:  <none>
API Version:  elbv2.k8s.aws/v1beta1
Kind:         TargetGroupBinding
Metadata:
  Creation Timestamp:  2024-04-24T18:29:01Z
  Finalizers:
    elbv2.k8s.aws/resources
  Generation:        1
  Resource Version:  88988643
  UID:               7121a4df-526e-410e-b48b-971352b3f780
Spec:
  Ip Address Type:  ipv4
  Networking:
    Ingress:
      From:
        Security Group:
          Group ID:  sg-0ff2ccd75dfcc5429
      Ports:
        Port:      30717
        Protocol:  TCP
  Node Selector:
    Match Labels:
      Environment:  staging
  Service Ref:
    Name:            callisto-web
    Port:            8080
  Target Group ARN:  arn:aws:elasticloadbalancing:eu-west-1:207997242047:targetgroup/k8s-stagingi-callisto-224c049c92/8c6c8fdc65818fd6
  Target Type:       instance
Status:
  Observed Generation:  1
Events:
  Type    Reason                  Age                From                Message
  ----    ------                  ----               ----                -------
  Normal  SuccessfullyReconciled  95s (x3 over 95s)  targetGroupBinding  Successfully reconciled
  
  
  
![image](https://github.com/kubernetes-sigs/karpenter/assets/149725919/3daf8186-886d-47c3-9182-6cdb1e5df21e)

**Comment by tzneal** [comment]
Do you have an existing load balancer (not AWS Load Balancer Controlled), that you are trying to use?  Do you haven an ingress resource, if so, can you include it?

**Comment by jonathan-innis** [comment]
@dewstyh Do you have an update here? It's tough for us to make progress on the bug without getting more information.

**Comment by dewstyh** [comment]
Hello sorry for lost of track on this issue, the issue has been solved, I've alb annotation target node labels and matched with that to register nodes under those targetgroups. then it's successfully registerd the instances( targets).

thanks
