### ISSUE TITLE
Increase NodePool requirements `maxItems`

### ISSUE THREAD

**Issue by NetanelK** [kubernetes-sigs/karpenter#1270]
### Description

**What problem are you trying to solve?**
While working on aws/karpenter-provider-aws#5779 I've reached the maximum limit of 30 requirements per node pool, to support more requirements from providers, the maxItems limit needs to be increased.

karpenter-provider-aws [tests](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/instancetype/suite_test.go#L268) should support combined instance type labels.

**How important is this feature to you?**
This feature is needed to expand karpenter abilities to select instances more granularly.

I'd be happy to contribute this small adjustment if approved.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by NetanelK** [comment]
cc @jonathan-innis

**Comment by jmdeal** [comment]
I believe this limit had to do with CEL limitations around cost estimation. @engedaam do you remember if this was the original reason?
