### ISSUE TITLE
Retain all previous versions of the documentation on karpenter.sh

### ISSUE THREAD

**Issue by ashrafguitoni** [kubernetes-sigs/karpenter#1287]
## Description

At the moment, only a small number of versions have their documentation accessible at http://karpenter.sh/. If I put a link to the docs for version N in some document accessible to my team, the link is sure to be invalid within a few months.

I hope there are no major technical limitations for retaining docs for all versions of karpenter on the website. Maybe there's no need to show all versions on the dropdown menus, but the links should still work.

**Comment by engedaam** [comment]
Currently, we maintain the 5 recent versions of the Karpenter docs for cleanliness and following Kubernetes documentation model. If you have need for the older version of the docs, the team recommends you go to the release tag of the `karpenter-provider-aws` repo https://github.com/aws/karpenter-provider-aws/tree/v0.27.6/website. This issue would also better suited for https://github.com/aws/karpenter-provider-aws/tree/main, as that repo holds the Karpenter.sh docs.

**Comment by ashrafguitoni** [comment]
Maybe referring to the contents in Github is best for us, then. Many thanks!
