### ISSUE TITLE
Provisioning cannot correctly evaluate topologySpreadConstraints

### ISSUE THREAD

**Issue by daimaxiaxie** [kubernetes-sigs/karpenter#1306]
### Description

**Observed Behavior**:

I have a deployment that replicas 4, pod has topologySpreadConstraints:
```yaml
topologySpreadConstraints:
- labelSelector:
    matchLabels:
      app: fake-xxxx
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
```

I modified kwok cloud provider to simulate our cluster. Kwok offer 4 zones: A, B, C, D. 
But my cluster only uses the B, C zone. (All nodepools specify topology.kubernetes.io/zone is B or C) 

When I apply deployment only scale up 2 node(B, C).

```bash
{"level":"ERROR","time":"2024-06-07T16:56:48.879+0800","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"app-c-ecs.r7.16xlarge\", daemonset overhead={\"pods\":\"1\"}, unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = C: 1 B: 1 and 1 other(s), podDomains = topology.kubernetes.io/zone Exists, nodeDomains = topology.kubernetes.io/zone In [C];  incompatible with nodepool \"app-b-ecs.r7.16xlarge\", daemonset overhead={\"pods\":\"1\"}, unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = C: 1 B: 1 and 1 other(s), podDomains = topology.kubernetes.io/zone Exists, nodeDomains = topology.kubernetes.io/zone In [B];,"commit":"355bc85","pod":"default/fake-app-86967cc997-2ccnq"}
```

**Expected Behavior**:

Scale up 4 nodes, 2 in B, 2 in C.

**Reproduction Steps** (Please include YAML):

A NodePool requirements `topology.kubernetes.io/zone in B`, A NodePool requirements `topology.kubernetes.io/zone in C`.

Pod add topologySpreadConstraints.

Modify kwok cloud provider offers A, B, C, D zone.

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): v1.28.8

**Explain**:
Can I eliminate this problem by switching to AWS CloudProvider? 
At the moment I think this is a problem with karpenter, it recognizes domins based on the cloud, while kube-scheduler is based on existing instances.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
> I modified kwok cloud provider to simulate our cluster. Kwok offer 4 zones: A, B, C, D.
> But my cluster only uses the B, C zone. (All nodepools specify topology.kubernetes.io/zone is B or C)

For this to work like you expect, you need to add a required node affinity for those two zones on the pods. That will restrict the topology, it can't be done by restricting at the nodepool.

**Comment by daimaxiaxie** [comment]
@tzneal Thanks, it works fine. 

A few thoughts, this will increase scheduler's work. Maybe karpenter should evaluate the zone of the cluster in a better way.

**Comment by tzneal** [comment]
When implementing it there were multiple options on how to interpret a provisioner selecting a subset of topology labels.  We chose to not interpret that as restricting the set of global topology domains (e.g. what would happen if another node existed in a managed node group with that domain, for a required constraints we would launch capacity and the scheduler would refuse to schedule).  This also enables topology spreading over multiple provisioners which has some valid use cases.
