### ISSUE TITLE
Consolidation policy for a nodepool selectable based on time/cron

### ISSUE THREAD

**Issue by Nadeshan** [kubernetes-sigs/karpenter#1310]
### Description

**Observed Behavior**:
We have stateful apps running in our K8s clusters and cant afford intermittent evictions by the consolidation policy - 'WhenUnderutilized'. So we are forced to use the policy Whenempty. This is causing inefficient node/resource utilization, even if we  scale down less important workloads during night time and weekends. There are many nodes with one or two workloads still running the whole weekend and causing unnecessary cost to us. We will have to change the consolidation policy for the nodepool by means of some external automation to tackle this. 
I also checked for existing feature requests for similar requirement, but couldnt find one. 

**Expected Behavior**:
It will be nice if karpenter nodepool settings have option to select consolidation policy based on a cron expresssion. It might be also good to include consolidation policy under disruption budgets, where we can already have cron expressions. So we can set WhenUnderutilized consolidation policy for night and weekends and have efficient resource utilization.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: latest
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
/remove-kind bug
/kind feature

> cant afford intermittent evictions by the consolidation policy - 'WhenUnderutilized'

I'd be curious to know what problems you're running into with `WhenUnderutilized`. Are you having availability issues due to evictions? Or do you find consolidation to be too aggressive?

**Comment by sftim** [comment]
I'd really love to see a contrib tool that manages NodePools based on a schedule. That way, we can find ways to fit every use case (rather than handling a good subset of them in Karpenter core, and leaving everyone else disappointed).
