### ISSUE TITLE
Karpenter fails to clean NodeClaim if K8s finalizers are removed before deleting the node

### ISSUE THREAD

**Issue by Heniland** [kubernetes-sigs/karpenter#1392]
### Description

**Observed Behavior**:

When attempting to delete a node from Kubernetes, if i remove finalizers manually then delete the node, Karpenter fails to clean up the corresponding NodeClaim. 
The node is removed from the K8s node object, but it remains in the Karpenter NodeClaim.

However, if I run delete command(which will fail because of finalizers), then remove the K8s finalizers and i run delete command again, Karpenter correctly cleans up the NodeClaim.

This create a scenario where a pods are scheduled to a non existing node 

**Expected Behavior**:
If i remove finalizers manually then delete the node, I expect Karpenter to remove the node from NodeClaim as well.

**Reproduction Steps** (Please include YAML):
1 - pick a node from nodeclaims
```shell
❯ kubectl get nodeclaims                                                                                                                                                                                             
NAME                        TYPE          ZONE         NODE                                         READY   AGE
...
testnode-worker-grcr6        c5d.9xlarge   eu-west-1b   ip-10-0-119-29.eu-west-1.compute.internal    True    2d22h
...
```

2 - check and remove finalizers
```
❯ kubectl get node ip-10-0-119-29.eu-west-1.compute.internal -o json | jq '.metadata.finalizers'                                                                                                                     
[
  "karpenter.sh/termination"
]

❯ kubectl patch node ip-10-0-119-29.eu-west-1.compute.internal -p '{"metadata":{"finalizers":[]}}' --type=merge                                                                                                      
node/ip-10-0-119-29.eu-west-1.compute.internal patched

❯ kubectl get node ip-10-0-119-29.eu-west-1.compute.internal -o json | jq '.metadata.finalizers'                                                                                                                     
null
```

3 - Delete the node
```
❯ kubectl delete node ip-10-0-119-29.eu-west-1.compute.internal                                                                                                                                                      
node "ip-10-0-119-29.eu-west-1.compute.internal" deleted
```

4 - The node is removed from k8s
```
❯ kubectl get node ip-10-0-119-29.eu-west-1.compute.internal                                                                                                                                                         
Error from server (NotFound): nodes "ip-10-0-119-29.eu-west-1.compute.internal" not found
```

5 - check the nodeclaims again, it's still here
```shell
❯ kubectl get nodeclaims                                                                                                                                                                                             
NAME                        TYPE          ZONE         NODE                                         READY   AGE
...
testnode-worker-grcr6        c5d.9xlarge   eu-west-1b   ip-10-0-119-29.eu-west-1.compute.internal    True    2d22h
...
```

**Versions**:
- Chart Version: `0.36.2`
- Kubernetes Version (`kubectl version`): `v1.28.9-eks-036c24b`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
I want to understand the use case here. Why do you want to remove the finalizer manually to delete the node?

**Comment by Heniland** [comment]
Hi @jigisha620 good question and I should have added it earlier.

We have queues of tasks that we pull into batches of jobs. Based on the queue size, we spin up nodes. For better resource utilization, we deployed a custom plugin based on [kube-descheduler](https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#highnodeutilization). We modified it to cordon low-utilized nodes rather than evicting pods, allowing jobs to finish and letting Karpenter remove the node once all jobs are done.

However, occasionally, some jobs finish their tasks but remain stuck in the running state (This is not a Karpenter-related issue). In such cases, where the node is cordoned, the task is done, but the job runs indefinitely, we implemented a timeout for cordoned nodes. If the job is not completed within the timeout, we need to delete the node programmatically.

This is where we discovered the problem.

The workaround we found is: if you delete the node before removing the finalizers, then remove the finalizers and delete the node again, it works.

Please let me know if you need more info, Thanks.

**Comment by jigisha620** [comment]
Ideally if you delete the node without removing the finalizer, it will trigger the termination flow for Karpenter which should cordon and drain the node. Why is it that flow not working? Are there any Karpenter logs that indicate why this deletion failed?

**Comment by Heniland** [comment]
Here are few logs and events I captured

Log:

`❯ kubectl logs karpenter-7dc45c94c9-k2znh --since-time=2024-07-06T06:09:54Z -n karpenter > karpenter.log`

[karpenter.log](https://github.com/user-attachments/files/16115115/karpenter.log)



Event:

`❯ kubectl get events --field-selector involvedObject.kind=Node,involvedObject.name=ip-10-0-104-120.eu-west-1.compute.internal -o json`                                                      

```json
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "count": 6875,
            "eventTime": null,
            "firstTimestamp": "2024-06-26T07:01:12Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Node",
                "name": "ip-10-0-104-120.eu-west-1.compute.internal",
                "resourceVersion": "389294468",
                "uid": "3cc96cab-b3a7-4416-aaee-14eb0b6ebe50"
            },
            "kind": "Event",
            "lastTimestamp": "2024-07-06T06:09:54Z",
            "message": "Cannot disrupt Node: PDB \"prometheus-scale/prometheus-scale-prometheus\" prevents pod evictions",
            "metadata": {
                "creationTimestamp": "2024-06-26T07:01:12Z",
                "name": "ip-10-0-104-120.eu-west-1.compute.internal.17dc7bcbad832fc7",
                "namespace": "default",
                "resourceVersion": "412767339",
                "uid": "47e00413-b3e9-4a6d-bd01-8a83586c3216"
            },
            "reason": "DisruptionBlocked",
            "reportingComponent": "karpenter",
            "reportingInstance": "",
            "source": {
                "component": "karpenter"
            },
            "type": "Normal"
        },
        {
            "apiVersion": "v1",
            "count": 6,
            "eventTime": null,
            "firstTimestamp": "2024-07-06T06:15:55Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Node",
                "name": "ip-10-0-104-120.eu-west-1.compute.internal",
                "resourceVersion": "412775342",
                "uid": "3cc96cab-b3a7-4416-aaee-14eb0b6ebe50"
            },
            "kind": "Event",
            "lastTimestamp": "2024-07-06T06:25:57Z",
            "message": "Failed to drain node, 10 pods are waiting to be evicted",
            "metadata": {
                "creationTimestamp": "2024-07-06T06:15:55Z",
                "name": "ip-10-0-104-120.eu-west-1.compute.internal.17df8b20d3816aad",
                "namespace": "default",
                "resourceVersion": "412793333",
                "uid": "91297344-6311-4bf0-a1b1-db575178e2fb"
            },
            "reason": "FailedDraining",
            "reportingComponent": "karpenter",
            "reportingInstance": "",
            "source": {
                "component": "karpenter"
            },
            "type": "Warning"
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}
```

**Comment by jigisha620** [comment]
From the log it seems like you have pod disruption budgets, that's preventing the node from being terminated. Can you share your nodePool configuration?

**Comment by Heniland** [comment]
@jigisha620 Here is the nodePool configuration

```
❯ kubectl describe nodepool worker
                                                                                                                                                                           
Name:         worker
Namespace:
Labels:       <none>
Annotations:  karpenter.sh/nodepool-hash: 1116874614643308375
              karpenter.sh/nodepool-hash-version: v2
API Version:  karpenter.sh/v1beta1
Kind:         NodePool
Metadata:
  Creation Timestamp:  2024-01-03T20:17:24Z
  Generation:          3
  Resource Version:    433004352
  UID:                 f5a1db5f-6414-4b6c-b189-e4e9fdf24149
Spec:
  Disruption:
    Consolidation Policy:  WhenUnderutilized
    Expire After:          720h
  Template:
    Metadata:
      Labels:
        Environment:    test
        OX Node:        Worker
        Owner:          Karpenter
        Pipeline Node:  false
    Spec:
      Node Class Ref:
        API Version:  karpenter.k8s.aws/v1beta1
        Kind:         EC2NodeClass
        Name:         worker
      Requirements:
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          spot
        Key:       karpenter.k8s.aws/instance-category
        Operator:  In
        Values:
          m
          r
          c
          d
          n
        Key:       topology.kubernetes.io/zone
        Operator:  In
        Values:
          eu-west-1b
        Key:       karpenter.k8s.aws/instance-cpu
        Operator:  Gt
        Values:
          31
        Key:       karpenter.k8s.aws/instance-cpu
        Operator:  Lt
        Values:
          97
        Key:       kubernetes.io/arch
        Operator:  In
        Values:
          amd64
        Key:       karpenter.k8s.aws/instance-hypervisor
        Operator:  In
        Values:
          nitro
        Key:       karpenter.k8s.aws/instance-generation
        Operator:  Gt
        Values:
          2
      Taints:
        Effect:  NoSchedule
        Key:     dedicated
        Value:   worker
Status:
  Resources:
    Cpu:                  36
    Ephemeral - Storage:  1048061956Ki
    Memory:               72487732Ki
    Pods:                 234
Events:                   <none>
```

**Comment by jigisha620** [comment]
Do you have any blocking pod disruption budgets? This log line indicates that a PDB is preventing pod eviction causing failure to drain the node.
```
check failed, can't drain node, PDB \"prometheus-scale/prometheus-scale-prometheus\" is blocking evictions
```
Removing `finalizer` is definitely not the right way to deal with this. By removing `finalizer` you end up breaking Karpenter's contract since it depends on finalizers to clean up resources.

**Comment by Heniland** [comment]
"Removing finalizer is definitely not the right way to deal with this" - I agree, I'm happy to fix it in a cleaner way possible.

About PDB, I noticed that we have the following

```
❯ kubectl get pdb pdb-cloner-service                                                                                                                                                 
NAME                 MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
pdb-cloner-service   N/A             0                 0                     69d
```
I will disable the PDB, thank you so much.

**Comment by sergii-auctane** [comment]
I have a similar issue, but I'm not trying to delete node claims. The problem is that Karpenter doesn't remove nodeclaims sometimes after the node is terminated by AWS, for example.  I would not care too much, but sometimes it stops creating new nodeclaims and nodes and starts again only when I remove those nodeclaims manually, but removing finalizers. 
Here is the description from the broken nodeclaim. 
```
Normal  DisruptionBlocked  4m31s (x632 over 39h)  karpenter  Cannot disrupt NodeClaim: state node doesn't contain both a node and a nodeclaim
```
