### ISSUE TITLE
metric karpenter_disruption_actions_performed_total does have value

### ISSUE THREAD

**Issue by hitsub2** [kubernetes-sigs/karpenter#1413]
### Description

**Observed Behavior**:
The karpenter_disruption_actions_performed_total is alway empty when there is disruption happened.

**Expected Behavior**:
karpenter_disruption_actions_performed_total should have value

**Reproduction Steps** (Please include YAML):

Spot interruption by AWS FIS, karpenter performing node evict and delete the node. But this metrics does not have any value.

**Versions**:
- Chart Version: karpenter-0.37.0
- Kubernetes Version (`kubectl version`):1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Karpenter's disruption metrics refer to voluntary disruption, e.g. drift, expiration, consolidation, and emptiness. Spot interruption is involuntary and not considered a disruption action. For the AWS provider at least, spot interruption can be tracked with [this metric](https://karpenter.sh/docs/reference/metrics/#karpenter_interruption_actions_performed).

/triage accepted
/kind support

**Comment by hitsub2** [comment]
but ccording to [the docs](https://karpenter.sh/docs/concepts/disruption/), spot interruption is just a method of disruption.
