### ISSUE TITLE
Run Karpenter Controller as single replica 

### ISSUE THREAD

**Issue by pelzerim** [kubernetes-sigs/karpenter#1414]
We are considering running Karpenter as a single replica.

As far as I can tell it scales vertically and the additional replicas just take over in case of failures. Is this correct? 

If we can accept the Xs it takes for a controller restart, there should be no hidden downsides? 

Is this assumption correct?  

Does information exist on how karpenter does HA and scaling?

**Comment by jmdeal** [comment]
This question is probably more appropriate for the providers than the library, but I can speak for AWS. You're correct, the additional replicas are only for failover, and there's nothing stopping you from running a single replica. That being said controller restarts are not the only reason to run multiple replicas, e.g. protecting against AZ outages. This is why the default configuration shipped with Karpenter's helm chart includes a zonal anti-affinity.
