### ISSUE TITLE
EC2 Instances configuration messed up when spawned by Karpenter, they fail to register to the cluster

### ISSUE THREAD

**Issue by nello1992** [kubernetes-sigs/karpenter#1419]
### Description

**Observed Behavior**:
Hi folks! I'm having troubles in spawning well-configured EC2 instances leveraging Karpenter.
Karpenter is correctly deployed into the EKS cluster and configured with a NodePool and an EC2NodeClass.

Their definitions are pretty simple:

- NodePool
![Screenshot 2024-07-15 at 12 04 19](https://github.com/user-attachments/assets/42f764c7-ff58-491e-ab4d-fdbc33dc8cbe)

- NodeClass
![Screenshot 2024-07-15 at 12 05 02](https://github.com/user-attachments/assets/f606e201-59bd-48ec-831e-6dd2543eb42d)

Whenever there are Pods in Pending state, Karpenter correctly spawns an EC2 instance and no ERRORS are shown from its logs.

The problem is that spawned instances are not configured correctly and therefore the kubelet doesn't start. E.g. kubelet is configured to use Docker as CR, cgroupfs instead of systemd, there is no configuration regarding the CNI (Cilium) under /etc/cni/net.d, and so on:
![Screenshot 2024-07-15 at 12 25 14](https://github.com/user-attachments/assets/22ee903c-77e4-4654-9c1c-77f3302353d4)

Also, I noticed that the correct configuration is located under /etc/eks:
![Screenshot 2024-07-15 at 12 22 15](https://github.com/user-attachments/assets/64a669af-da15-4716-8890-93cb5f6b2746)

Outcome: the EC2 instance doesn't get registered to the cluster and, indeed, it doesn't get displayed as cluster node.

I'm using the same AMI used by the Nodegroup already attached to the EKS Cluster, so I expect the same configuration is applied. Same problem happens with family AL2023.

Example of NodeClaim generated:
![Screenshot 2024-07-15 at 13 22 13](https://github.com/user-attachments/assets/27474d9d-a83b-48c0-b988-1a97906372eb)

Any suggestions or guidelines to how to troubleshoot it?

**Expected Behavior**:
I expect that once Karpenter spawn an EC2 instance, it's gonna be configured and initialised correctly, and therefore joined to the cluster correctly.

**Reproduction Steps** (Please include YAML):
1. Create an EKS cluster with Cilium CNI and with a Nodegroup attached to it
2. Deploy karpenter using helm
3. Deploy NodePool and NodeClass as described above
4. Create a number of pods that requires 1 or more nodes to be scheduled on. In this way Karpenter should spawn at least one more EC2 instance
5. Check wether the EC2 instance is configured correctly and joins the cluster

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.30

**Comment by jmdeal** [comment]
Could you reopen this issue against the [AWS provider repo](https://github.com/aws/karpenter-provider-aws)? When you do please include your full NodeClass spec and status, along with the UserData used when launching the instance (easiest way to grab this is through the EC2 console). I'm going to close the issue out here since this is outside the scope of the upstream library.

/close
