### ISSUE TITLE
karpenter reentrancy during the NodeClaim lifecycle

### ISSUE THREAD

**Issue by daimaxiaxie** [kubernetes-sigs/karpenter#1448]
### Description

**Observed Behavior**:

When karpenter restarts(panic) during `launchNodeClaim`, it causes repeated instances to be started. Also, instances are difficult to find.

**Expected Behavior**:

Even if the karpenter crashes, only one instance is started.

**Reproduction Steps** (Please include YAML):

Karpenter with kwok:

1. Add panic after `l.cloudProvider.Create`(`launchNodeClaim`).
2. Apply pod, pod pending.
3. Karpenter panic occurred.   At this time, there are NodeClaim and fake node in the cluster.
4. Delete panic in karpenter. Restart Karpenter.
5. Karpenter again create fake node.
6. There are NodeClaim twice as many fake node in the cluster.

*1 NodeClaim launch 2 node*
```bash
~$ kubectl get nodeclaims.karpenter.sh  -o wide
NAME                       TYPE         ZONE        NODE                    READY   AGE   CAPACITY   NODEPOOL             NODECLASS
app-host-prod-auto-r56r5   c7.8xlarge   C           keen-gauss-1753340741   True    40s   spot       app-host-prod-auto   default

~$ kubectl get nodes
NAME                              STATUS   ROLES           AGE   VERSION
inspiring-williamson-2908581107   Ready    <none>          43s   kwok-v0.3.0
keen-gauss-1753340741             Ready    <none>          15s   kwok-v0.3.0
```

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.28.8

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by daimaxiaxie** [comment]
We need to strengthen the mapping relationship between NodeClaim and EC2.
A possible solution:

1. Fill NodeClaim.UID in EC2 tag during launch.
2. The NodeClaim with UID returned by `CloudProvider.List`.   *UID is obtained from tag in instanceToNodeClaim.*

**Comment by engedaam** [comment]
Currenlty, NodeClaims track the instance id that is launched in the status condition. Are you seeing the instances launched to have nodeclaim the same nodeclaim tags?

**Comment by daimaxiaxie** [comment]
When I use Karpenter with AWS:

Stop `nodeclaimgarbagecollection` in AWS provider, add panic in Karpenter.

1. before panic
```bash
$ kubectl get nodeclaims.karpenter.sh
No resources found
$ kubectl get nodes
NAME                                               STATUS   ROLES    AGE   VERSION
ip-10-XX-149-233.ap-southeast-1.compute.internal   Ready    <none>   23h   v1.28.8-eks-ae9a62a
$
```
2. panic
```bash
$ kubectl get nodeclaims.karpenter.sh
NAME            TYPE   ZONE   NODE   READY     AGE
default-s56fk                        Unknown   28s
```
```bash
# log
{"level":"INFO","time":"2024-07-27T19:10:34.577+0800","logger":"controller","caller":"provisioning/provisioner.go:145","message":"created nodeclaim","commit":"490ef94-dirty","controller":"provisioner","NodePool":{"name":"default"},"NodeClaim":{"name":"default-s56fk"},"requests":{"cpu":"4180m","memory":"16504Mi","pods":"6"},"instance-types":"m5a.2xlarge"}
{"level":"INFO","time":"2024-07-27T19:10:36.750+0800","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"490ef94-dirty","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-s56fk"},"namespace":"","name":"default-s56fk","reconcileID":"a30e6f99-7f62-48e0-9a0c-7f2b0600XXXX","provider-id":"aws:///ap-southeast-1b/i-0b8cf14a1000dd768","instance-type":"m5a.2xlarge","zone":"ap-southeast-1b","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"29317Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
```
3. restart
```bash
{"level":"INFO","time":"2024-07-27T19:11:32.185+0800","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"490ef94-dirty","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-s56fk"},"namespace":"","name":"default-s56fk","reconcileID":"0276de18-890f-445c-b28c-99fc6742XXXX","provider-id":"aws:///ap-southeast-1b/i-0f0f9d926b5c639cd","instance-type":"m5a.2xlarge","zone":"ap-southeast-1b","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"29317Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
```

The launched instances have the same nodeclaim tag.

When aws nodeclaimgarbagecollection is enabled, redundant instances will be recycled. But this is an enhancement of AWS CloudProvider, not a mandatory requirement of Karpenter.

**Comment by njtran** [comment]
If you inject a panic right after the results of the Launch call in AWS, then you might see the NodeClaim StatusCondition fail to mark as launched, but a node would still join the cluster if it succeeds. This would be an orphaned node, and should be garbage collected by the AWS. 

I think the way this could be extended to upstream would be to have a garbage collection controller in this upstream library, that does a cloudprovider.Get() call on the nodes that have the Karpenter label, but don't have a nodeclaim with matching provider ID. We'd get the cloudprovider.Instance that matches the node, see it's owned by Karpenter, but see it doesn't have a nodeclaim, and then we try and reconcile this. Ultimately, this seems like a very very very low-chance occurrence. @daimaxiaxie have you run into this in your clusters? Or are you just testing different ways that non-standard AWS Karpenter installations will work? I agree we can probably make this concept cloud provider agnostic, but wondering if it's an active issue for you.

**Comment by daimaxiaxie** [comment]
Yes, I'm just testing it right now. It's not an urgent issue.
