### ISSUE TITLE
Enhance v1 NodeClaim print output to show node kubernetes version

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes-sigs/karpenter#1463]
### Description

**What problem are you trying to solve?**
As a cluster admin, when I am upgrading a cluster's kubernetes version, it would be convienent to have the Karpenter nodeclaim status and wide print output show the associated node's kubernetes short version string, if it exists. 

**How important is this feature to you?**
This feature would make it easier to track the progress of cluster upgrades when nodes are being replaced with drift. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
I think we'd have to add this into the status of the nodeclaim. FWIW, this info should be visible on the node. Is there any reason you need it on the nodeclaim?

**Comment by fmuyassarov** [comment]
@njtran 
Would you be interested to have this change ? If yes I can file a PR for it.

**Comment by njtran** [comment]
I'd want to understand first if this is something that's solved by having it on the node.

**Comment by cnmcavoy** [comment]
The use case here is upgrading workers to a new major kubernetes version. It is difficult to tell what nodeclaims are on the new upgrade version vs the previous kubernetes version at a glance in a cluster, making it hard to tell if a cluster has been completely upgraded. Checking the drifted status is insufficient, as nodes can drift for other reasons.

I agree the info is visible on the node, but it doesn't tell you at a glance, you have to cross-reference each nodeclaim.
