### ISSUE TITLE
Consolidate node whenEmpty if only daemonsets are left

### ISSUE THREAD

**Issue by mkinley-life360** [kubernetes-sigs/karpenter#1475]
### Description

**What problem are you trying to solve?**

We are creating a nodepool for a service deployment that has an affinity set to have one pod per node but each node is also getting our monitoring daemonsets added to it. We want to be able to consolidate the node once this pod is no longer provisioned but it seems it never reaches the WhenEmpty status as the daemonsets are still running on the node. Is there any way to tell karpenter to scale down the node if only daemonsets are left?

**How important is this feature to you?**

Would greatly appreciate some more flexiblity with these settings to handle this use case.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Karpenter should already do this. https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/utils/pod/scheduling.go#L42

Can you share your events for the node, karpenter controller logs, and pods on the node?

**Comment by mkinley-life360** [comment]
@njtran  Hi Nick, Thanks for validating this for me. I reviewed again and found that there was actually a replicaset being scheduled on that node I didn't notice before. Once I removed this replicaset, it starting killing nodes with only daemonsets left.
