### ISSUE TITLE
StartupTaints not working properly 

### ISSUE THREAD

**Issue by dhanutalari** [kubernetes-sigs/karpenter#1479]
### Description
In order to get the secrets from the Secret Manager for my workload pod, the AWS Secret Store CSI Driver DaemonSet pod needs to be running on the node before my workload pod starts. So, I am using startup taints for this. However, I have observed the following issue: the node status shows "NotReady" and the node does not get initialized because the startup taints are not removed after the DaemonSet pods are running.

To run the DaemonSet pod on the node, it needs to have the label app=kong and the taint app=kong, which I have added accordingly.

**Observed Behavior**:
The provisioned node is not getting the status "Initialized." The node gets registered, and pods are running, but the node status shows "NotReady." Even after all my workload pods are deleted, my node is not able to delete automatically.

**Expected Behavior**:
Startup taints need to be removed after DaemonSets are running, and the node needs to be initialized and deletes automatically after workload pods deleted. 

**Reproduction Steps** (Please include YAML):
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: dynamic-env
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 240h
    budgets:
    - nodes: 10%
  template:
    metadata:
      labels:
        app: kong
        nodeselect: dynamic-env
        env: nonprod
        project: marketplace
        product: b2c
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m","r","t"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: dynamic-env-ec2nodeclass
      startupTaints:
        - key: app
          value: kong
          effect: NoSchedule

**Versions**:v0.37
- Chart Version: v0.37
- Kubernetes Version (`kubectl version`): v1.29.3

Please find the nodeclaim conditions below. 
Conditions:
    Last Transition Time:  2024-07-30T06:58:50Z
    Message:               StartupTaint "app=kong:NoSchedule" still exists
    Reason:                StartupTaintsExist
    Status:                False
    Type:                  Initialized
    Last Transition Time:  2024-07-30T06:58:19Z
    Message:               
    Reason:                Launched
    Status:                True
    Type:                  Launched
    Last Transition Time:  2024-07-30T06:58:36Z
    Message:               Initialized=False
    Reason:                UnhealthyDependents
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-07-30T06:58:36Z
    Message:               
    Reason:                Registered
    Status:                True
    Type:                  Registered

Please clarify the following questions:

1 Does Karpenter consider DaemonSet pods as workload pods?
2 Do DaemonSet pods cause the node to not delete if workload pods are not present?
3 Can you share any documents on how startup taints work, with examples?

**Comment by njtran** [comment]
If startup taints aren't removed, Karpenter doesn't consider a node initialized. This is because startup taints are used to ensure that node-critical workloads are running before anything else. Karpenter assumes that the controller responsible for removing that taint will do so when it's completed it's necessary setup.  Are you orchestrating this manually?
