### ISSUE TITLE
Add ability to set dynamic value for `kubeReserved` cpu

### ISSUE THREAD

**Issue by jukie** [kubernetes-sigs/karpenter#1518]
### Description

**What problem are you trying to solve?**
I'd like the ability to set a common kubelet configuration value for maxPods and kubeReserved.memory but would like to retain the dynamic cpu configuration that's used in the [eks bootstrap.sh
](https://github.com/awslabs/amazon-eks-ami/blob/62c3103c9e282b6f67fbd5865512c962f93ae784/templates/al2/runtime/bootstrap.sh#L280-L289). This is because settings kubelet.maxPods alone doesn't lead to any changes in kubelet.kubeReserved as those values will still be generated based on `/etc/eks/eni-max-pods.txt`

If I only set kubeReserved.memory kubelet will fail to start due to an invalid config and if I override the value in bootstrap.sh during userdata execution Karpenter is then unaware of the actual values when making scheduling decisions.

Is there a way to configure a NodePool in a way that would allow for setting a static value for kubeReserved.memory while also allowing for the dynamic CPU configuration from bootstrap.sh?
```
# Calculates the amount of CPU to reserve for kubeReserved in millicores from the total number of vCPUs available on the instance.
# From the total core capacity of this worker node, we calculate the CPU resources to reserve by reserving a percentage
# of the available cores in each range up to the total number of cores available on the instance.
# We are using these CPU ranges from GKE (https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#node_allocatable):
# 6% of the first core
# 1% of the next core (up to 2 cores)
# 0.5% of the next 2 cores (up to 4 cores)
# 0.25% of any cores above 4 cores
# Return:
#   CPU resources to reserve in millicores (m)
get_cpu_millicores_to_reserve() {
  local total_cpu_on_instance=$(($(nproc) * 1000))
  local cpu_ranges=(0 1000 2000 4000 $total_cpu_on_instance)
  local cpu_percentage_reserved_for_ranges=(600 100 50 25)
  cpu_to_reserve="0"
  for i in "${!cpu_percentage_reserved_for_ranges[@]}"; do
    local start_range=${cpu_ranges[$i]}
    local end_range=${cpu_ranges[(($i + 1))]}
    local percentage_to_reserve_for_range=${cpu_percentage_reserved_for_ranges[$i]}
    cpu_to_reserve=$(($cpu_to_reserve + $(get_resource_to_reserve_in_range $total_cpu_on_instance $start_range $end_range $percentage_to_reserve_for_range)))
  done
  echo $cpu_to_reserve
}
```

**How important is this feature to you?**
Very important and would be willing to contribute this feature

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
/retitle Add ability to set dynamic value for `kubeReserved` cpu

(because this is a feature request)

**Comment by jukie** [comment]
For anyone else hitting this you can work around it by adding to KUBELET_EXTRA_ARGS in /etc/eks/bootstrap.sh during user data execution.

```
    sed -i 's/args="$KUBELET_EXTRA_ARGS"/args="--kube-reserved=\\"cpu=\${cpu_millicores_to_reserve}m\\" $KUBELET_EXTRA_ARGS"/g' /etc/eks/bootstrap.sh
```

**Comment by njtran** [comment]
> dynamic CPU configuration from bootstrap.sh?

What sort of dynamic configuration are you looking to have? This would be a departure from what the [upstream kubelet structure](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration:~:text=kubeReserved%20is%20a,details.%20Default%3A%20nil) is.

**Comment by jukie** [comment]
What I mean is Dynamic within a NodePool based on the selected instance type, not a dynamic value for Kubelet itself. For example I linked the bootstrap.sh example which would update the kubelet config file during user data execution.
My use case is to specify a memory reservation that scales with maxPods but CPU doesn't so I'd like to retain the dynamic setup.

The aws provider [does this](https://github.com/aws/karpenter-provider-aws/blob/e36e74769fc38ddc19e7cfc4df4b7fa7c747c4ae/pkg/providers/instancetype/types.go#L369-L402) seemingly does this when computing an instance type's kubeReserved but doesn't explicitly add this to kubelet cli flags for userdata so if a user only specifies kubeReserved.memory then cpu and ephemeral-storage will be read as null.

**Comment by njtran** [comment]
Typically memory for kube-reserved scales with pod density, and CPU scales with the number of cores. Seems that your use-case is that you think memory shouldn't scale, but CPU should. Considering that this seems to be a function of how AWS AMI Families handle overrides, I'd want to discuss this in the AWS provider issue that you opened up, especially since we've moved the `kubelet` to EC2NodeClass at v1 anyway. 

I'll close this in favor of https://github.com/aws/karpenter-provider-aws/issues/6665
