### ISSUE TITLE
logOutputPaths and logErrorOutputPaths not working

### ISSUE THREAD

**Issue by mariuskimmina** [kubernetes-sigs/karpenter#1572]
### Description

**Observed Behavior**:

I am using aws [helm chart](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml) and I  changing the values for `logOutputPath` and `logErrorOutputPath`  (Note, not sure if this issue belongs here or in `karpenter-provider-aws`)

Changing these values does not seem to have any effect. 

I have been trying the following (using Terraform)

```
  set {
    name  = "logOutputPaths[0]"
    value = "/var/log/containers/output.log"
  }

  set {
    name  = "logErrorOutputPaths[0]"
    value = "/var/log/containers/errors.log"
  }
```

But the logs still seem to end up in stdout only. 
I searched the repo and found that these values are used here in _helpers.tpl

```
{{/*
Flatten the stdout logging outputs from args provided
*/}}
{{- define "karpenter.outputPathsList" -}}
{{ $paths := list -}}
{{- range .Values.logOutputPaths -}}
    {{- if not (has (printf "%s" . | quote) $paths) -}}
        {{- $paths = printf "%s" . | quote  | append $paths -}}
    {{- end -}}
{{- end -}}
{{ $paths | join ", " }}
{{- end -}}
```

But I couldn't find any other reference to `karpenter.outputPathsList` Which makes me believe that this value may not be used at all? 

This seems to be related: https://github.com/aws/karpenter-provider-aws/pull/6586/files
While `logConfig.outputPaths` was replaced with `logOutputPaths` all references to `karpenter.outputPathsList` have been removed

**Expected Behavior**:

I'd expect the `logOutputPaths` and `logErrorOutputPaths` configurations to work and karpenter to write its logs to these paths.

**Reproduction Steps** (Please include YAML):

**Versions**:

Chart version
```
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "0.37.0"
```

Kubernetes version
```
Client Version: v1.28.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-eks-db838b0
```

Also related: https://github.com/aws/karpenter-provider-aws/issues/5352

**Comment by mariuskimmina** [comment]
Welp, I just noticed that v0.37.0 still has the old `logConfig` - so that explains why nothing was happening for me. 
The point still stands tho that I couldn't find any reference for `karpenter.outputPathsList` in the current main branch

**Comment by rschalo** [comment]
Hi @mariuskimmina - `karpenter.outputPathsList` was dropped in main in favor of `logOutputPaths` and `logErrorOutputPaths`. Were those not working as expected?

**Comment by mariuskimmina** [comment]
Hi @rschalo , so my problem simply was that I was trying to use `logOutputPaths` (because I was looking at latest values.yaml) while using v0.37.0 of the helm chart - so for the solution was to simply use the old `logConfig` 
While I was trying to figure out why `logOutputPaths` weren't working for me, I tried to figure out how these are used and couldn't find any reference of `logOutputPaths` other than in `values.yaml` and `_helpers.tpl` file - so if these work, then I don't understand how. 

That said, this issue was mostly the result of me being confused by looking the latest values.yaml while using v0.37.0 - so it can be closed.

**Comment by mariuskimmina** [comment]
Hi again @rschalo , as karpenter v1 got released today we just tested it out on one of our test environments and `logOutputPaths` indeed don't seem to be working properly. I see logs only going to stdout even tho we configured an addtional path.

**Comment by rschalo** [comment]
@jonathan-innis Mind adding `triage/accepted` here? I'll look into the changes needed in the `_helpers.tpl` to make this happne.

**Comment by joshuabaird** [comment]
This is also an issue for us (and a blocker for upgrading) -- it doesn't seem like `logOutputPaths` or `logErrorOutputPaths` are actually being implemented anywhere.  So - it's not possible to send logs to a file or anywhere other than the default stdout/stderr.

**Comment by mariuskimmina** [comment]
Great to see that a fix for this has been merged, thank you @rschalo
When do you think the next release will happen? We are eager to try out v1

**Comment by rschalo** [comment]
We are working on a patch. _Should_ be in the next week.

**Comment by calvinbui** [comment]
the fix was not included in 1.0.2

**Comment by joshuabaird** [comment]
Yes, it was included in v1.0.2 of the Helm chart -- it's just missing from the release notes.

**Comment by rschalo** [comment]
> the fix was not included in 1.0.2

While this was merged to main, it was missed when backporting different fixes for the latest round of patches. We're working on the next round of patches now and will have this included. Here is the PR that backported it into the next patch release: https://github.com/aws/karpenter-provider-aws/blob/release-v1.0.x/charts/karpenter/templates/deployment.yaml

**Comment by mariuskimmina** [comment]
Seems like the fix was also not included in 1.0.3

**Comment by rschalo** [comment]
We're working on a few tests at the moment for the patch that includes this but had to get that commit out in a patch last night. There's another patch in the works right now, thank you for your continued patience.

**Comment by mariuskimmina** [comment]
I think this can be closed, with version 1.0.6 the problem seems to be fixed.

**Comment by vijayck2020** [comment]
@mariuskimmina Can you please share your configuration
I am currently using the 1.0.6 and have configured it as below
=============================
        - name: LOG_LEVEL
          value: info
        - name: LOG_OUTPUT_PATHS
          value: "/var/log/controller.log"
        - name: LOG_ERROR_OUTPUT_PATHS
          value: stderr
        - name: METRICS_PORT
          value: "8000"
=============================

Since I am running karpenter in a fargate node, configured a ephemeral volume to be shared between controller and fluentbit containers. But the karpenter is not writing any logs to the configured file.

**Comment by mariuskimmina** [comment]
```
 - name: LOG_LEVEL
   value: info                                                                                                                                                                                                                 
 - name: LOG_OUTPUT_PATHS     
   value: stdout,/var/log/containers/output.log                    
- name: LOG_ERROR_OUTPUT_PATHS      
  value: stderr,/var/log/containers/errors.log
```
