### ISSUE TITLE
Karpenter Not Propagating Labels to nodes

### ISSUE THREAD

**Issue by Harphies** [kubernetes-sigs/karpenter#1580]
### Description

**Observed Behavior**:
Karpenter Not Propagating Labels defined in node groups down to nodes

**Expected Behavior**:
Labels defined in node group should be propagated down to nodes as it was in previous versions before v1.0.0.
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v1.0.0
- Kubernetes Version (`kubectl version`): v1.3.0

**Comment by jigisha620** [comment]
Hi @Harphies,
Can you share steps to reproduce this issue?

**Comment by Harphies** [comment]
I think everything is ok now. I'll close. Thank you

**Comment by javidaslan7s** [comment]
@Harphies I am facing the same issue, could you please elaborate what was the issue for you?
