### ISSUE TITLE
Existing Pods go to pending state and nodes get terminated

### ISSUE THREAD

**Issue by janani2019** [kubernetes-sigs/karpenter#1611]
### Description

**Observed Behavior**:
The nodes expire after 19m ( expireAfter is set to 19m) even though the pods are scheduled on them. The existing pods on the nodes go to pending state and waits for a new node to come up and they are scheduled on the new nodes.
**Expected Behavior**:
The pods should not go to pending state as it disrupts the application. The nodes should not be terminated if the pods are running on the nodes.
**Reproduction Steps** (Please include YAML):
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      expireAfter: 19m
      terminationGracePeriod: 20m
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["c", "m", "r"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["2"]
      - key: node.kubernetes.io/instance-type
        operator: Exists
        minValues: 10
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 20m

**Versions**:
- Chart Version: v1.1.0 (karpenter)
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by leoryu** [comment]
If your pod is important and you don't the pod's node is drifted when it's running. You can try to set `karpenter.sh/do-not-disrupt` annotation on your pod, karpenter will check this annotation:

https://github.com/kubernetes-sigs/karpenter/blob/14f12dd82b6c8dfc9bff634df0527ae718faa748/pkg/utils/pod/scheduling.go#L176-L181
