### ISSUE TITLE
Issue while downgrading Karpenter

### ISSUE THREAD

**Issue by vipul0805** [kubernetes-sigs/karpenter#1622]
Version
Karpenter Version: v0.37.0

Kubernetes Version: v1.3

Expected Behavior
Get CR's after applying the CRD.

Actual Behavior
Not able to get CR's after applying the v1beta1 CRD's. I was rolling back karpenter from v1.0.0 -> 0.37.0 and removed all the components in my cluster and did a fresh installation. 

I am seeing this error while getting the nodeclaims and ec2nodeclasses
```
Error from server: request to convert CR from an invalid group/version: karpenter.k8s.aws/v1
```

Can anyone please help me identify what's wrong here.

**Comment by knadsady** [comment]
I have the same issue. @vipul0805, was this closed because you figured it out?

**Comment by vipul0805** [comment]
Hi @knadsady, Yes I closed this issue. While attempting to roll back, I deleted v1 the nodes forcefully by removing the finalizers, but the underlying `nodeclaims` and `nodeclasses` were not deleted, resulting in the above error. After deleting the v1 resources, I could list the `v1beta1` resources.
