### ISSUE TITLE
ConsolidationPolicy: WhenEmpty

### ISSUE THREAD

**Issue by jderieg** [kubernetes-sigs/karpenter#1647]
### Description

I originally posted this in Discussions, but it got no traction there, so posting it here. I think it may be a bug because it definitely does not behave as expected.

**Observed Behavior**:
I've been testing the WhenEmpty policy, but it does not seem to be behaving as expected if the consolidateAfter setting is any more than about 2 to 3 minutes. My disruption settings look like this:

```
    disruption:
      consolidationPolicy: WhenEmpty
      consolidateAfter: 10m
      expireAfter: 360h
```

As a test, I scale up a deployment to a large number of pods in my nodegroup so that Karpenter spins up a new node. That works fine. When I scale the deployment back down to 0, I would expect Karpenter to scale down (remove) the Karpenter node after 10m of that deployment no longer needing it. That never happens. I've let it sit for over 24 hours and it never removes the node, even though there aren't anymore workloads added to the node to keep it alive. The strange thing is, if I set that consolidateAfter value to 2m or under, it works as I would expect, and removes the node. I'm running Karpenter v0.37.

**Expected Behavior**:
Consolidate the node(s) after the time specified in 'consolidateAfter'

**Reproduction Steps** (Please include YAML):
```
    disruption:
      consolidationPolicy: WhenEmpty
      consolidateAfter: 10m
      expireAfter: 360h
```

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by leoryu** [comment]
What dose your `budgets` looks like?

**Comment by jonathan-innis** [comment]
> That never happens. I've let it sit for over 24 hours and it never removes the node, even though there aren't anymore workloads added to the node to keep it alive

Can you share the spec/status of the node when it was left around for 24h? There's a couple fields `lastPodEventTime` and the `conditions` block that should give us a little more info. Karpenter will add a `Consolidatable` status condition after the pod has surpassed its `consolidateAfter`. If that doesn't get added, that means that the `lastPodEventTime` is too close. 

If that's not the behavior and the `lastPodEventTime` has truly surpassed your `consolidateAfter`, then yeah, that definitely seems like a bug.

**Comment by jderieg** [comment]
OK, thanks for that additional info. So the first thing I did was I upgraded Karpenter to v1 (specifically, I'm running version 1.0.2 on both the CRD's and Karpenter itself). I thought maybe that would fix it but the problem appears to still be present in Karpenter v1.
My Karpenter spec looks like this (really the same as before, but with the syntax changes for v1):

```
spec:
  disruption:
    budgets:
      - nodes: 100%
    consolidateAfter: 10m
    consolidationPolicy: WhenEmptyOrUnderutilized
```

I ran the same test, where I scaled a test deployment until Karpenter created a node for any pods that couldn't schedule. That part all works fine. I let it run for a little bit, and then scaled down the deployment.
At that point, I waited 10 minutes to see if anything changed. No logs were added in the Karpenter pod, and the node kept running. It's now been nearly 24-hours, and the node is still running.

Here is the 'conditions' block that you asked for. I'm not seeing any 'Consolidatable' status:

```
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 20 Sep 2024 10:35:45 -0600   Thu, 19 Sep 2024 14:10:10 -0600   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 20 Sep 2024 10:35:45 -0600   Thu, 19 Sep 2024 14:10:10 -0600   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 20 Sep 2024 10:35:45 -0600   Thu, 19 Sep 2024 14:10:10 -0600   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 20 Sep 2024 10:35:45 -0600   Thu, 19 Sep 2024 14:10:23 -0600   KubeletReady                 kubelet is posting ready status
```

I should also note that if I manually edit the NodePool configuration yaml on the cluster, and set any of those disruption values to _anything_ else, Karpenter then consolidates the node. Maybe that's by design, I'm not sure, but at least I can manually get rid of the node if I need to.
Thanks for your help!
