### ISSUE TITLE
panic: mkdir /tmp/kubebuilder-envtest: read-only file system

### ISSUE THREAD

**Issue by helen-frank** [kubernetes-sigs/karpenter#1651]
### Description

**Observed Behavior**:

**Expected Behavior**:
karpenter pod runing
**Reproduction Steps** (Please include YAML):
```
# make apply
...

# kubectl -n kube-system get pod | grep karpenter
karpenter-5fdbd7dd77-frzhg                 0/1     Error     1 (7s ago)   13s
# kubectl -n kube-system logs -f karpenter-5fdbd7dd77-frzhg
panic: mkdir /tmp/kubebuilder-envtest: read-only file system

goroutine 1 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/testing/addr.init.0()
        sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/testing/addr/manager.go:57 +0x15c

```

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): v1.31.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by helen-frank** [comment]
/assign

I'll try to fix that.

If anyone else knows of a solution to this problem, I'd appreciate it.

**Comment by helen-frank** [comment]
I'm guessing it was caused by this change https://github.com/kubernetes-sigs/karpenter/commit/75fcd2abcae13b7677a2c4d9ee2799662b2e9445

My pr https://github.com/kubernetes-sigs/karpenter/pull/1623 hasn't run `git fetch all; git rebase upstream/main`, so the `make apply` test is fine.

**Comment by jonathan-innis** [comment]
Fixed by https://github.com/kubernetes-sigs/karpenter/pull/1660. Looks like we (I) unintentionally imported something that added `envtest` to our dependency graph...and broke everything :)

Fixed now.
