### ISSUE TITLE
NodePool and NodeClass in Not Ready state

### ISSUE THREAD

**Issue by talhermon** [kubernetes-sigs/karpenter#1890]
### Description

**Observed Behavior**:
My cluster worked properly with a stable configurations - for some reason, I got this error surprisingly.

error retrieving attempts data due to: no attempts initialized. NewAttempt() should be called first. Skipping Throughput metrics{"level":"ERROR","time":"2024-12-18T17:09:22.173Z","logger":"controller","message":"ec2 api connectivity check failed","commit":"0a85efb","error":"operation error EC2: DescribeInstanceTypes, get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sts.us-east-1.amazonaws.com/\": dial tcp: lookup sts.us-east-1.amazonaws.com on 172.20.0.10:53: read udp 10.110.13.224:35778->172.20.0.10:53: read: connection refused"}
--
After that, the karpenter pod log indicates that it couldn't terminate one of the nodes 

error | operation error EC2: TerminateInstances, https response error StatusCode: 403, RequestID: e017c6b5-016c-4b06-9589-54f7cb56fdaf, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::060795918973:assumed-role/karpenter-dev/1734542110949936074 is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-1:060795918973:instance/* because no identity-based policy allows the ec2:TerminateInstances action. Encoded authorization failure message: X

From there on my node pools and node class entered into a not-ready state and the ec2 that failed to terminate still existed in the cluster and disappeared from the ec2 console.

Also, karpenter pods got into the CrashLoopBack state. 

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):
Remove the finalizer of the hanging node and delete the node claim. Karpenter pods were able to start.
NodePool and NodeClass were still not ready, so we had to recreate them.
**Versions**: EKS 1.31
- Chart Version: v1.1.0
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Since this is an EC2 authentication error, could you reopen the issue in [aws/karpenter-provider-aws](https://github.com/aws/karpenter-provider-aws)? I'm going to close the issue here.

/close
