### ISSUE TITLE
Can we avoid `context cancelled` on Singleton Controllers?

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#238]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.25.0

### Expected Behavior

When a controller goes through graceful termination in controller-runtime, the expectation is that controller-runtime will let all workers that are currently processing `reconcile.Requests` finish so that some reconciles do not complete in a weird "half-state (see https://github.com/kubernetes-sigs/controller-runtime/issues/764)

### Actual Behavior

Right now, with our singleton controller design, we exit out of the loop and pass the cancelled context through, meaning that we will get context cancelled as soon as the shutdown signal is received.

I wonder if there's a way to avoid errors like below so that we can successfully complete reconciliation similar to controller-runtime.

### Steps to Reproduce the Problem

1. Install Karpenter with interruption handling or provisioning enabled
2. Terminate Karpenter controller pods
3. Observe in the logs that you will see `context cancelled` logs for any controllers that implement the Singleton controller mechanism

### Resource Specs and Logs

```console
2023-03-10T20:31:31.740Z        INFO    controller      All workers finished    {"commit": "ffc7705-dirty", "controller": "termination", "controllerGroup": "", "controllerKind": "Node"}
2023-03-10T20:31:31.740Z        ERROR   controller.interruption getting messages from queue, receiving sqs messages, RequestCanceled: request context canceled
caused by: context canceled     {"commit": "ffc7705-dirty"}
2023-03-10T20:31:31.740Z        INFO    controller.interruption stopping controller     {"commit": "ffc7705-dirty"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sadath-12** [comment]
on the way to it

**Comment by sadath-12** [comment]
What time of solution do you expect @jonathan-innis is it capturing the shutdowns and adding timeouts or we could do something different ?

**Comment by sadath-12** [comment]
I can think of 2 things currently , one is the traditional timeout way and the other one is like keeping track of currently active reconcillations and when we recieve the shutdown signal we try avoid other reconciles and wait for active reconciles to end via something like ```sync.WaitGroup```

**Comment by AlekseiTikhonov-azur** [comment]
Same problem.
version  0.37.0

```
{"level":"INFO","time":"2024-10-17T09:51:44.329Z","logger":"controller","message":"Shutdown signal received, waiting for all workers to finish","commit":"490ef94","controller":"provisioner.trigger.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"ERROR","time":"2024-10-17T09:51:44.329Z","logger":"controller","message":"Reconciler error","commit":"490ef94","controller":"interruption","error":"getting messages from queue, receiving sqs messages, RequestCanceled: request context canceled\ncaused by: context canceled"}```
