### ISSUE TITLE
`cluster_state` Observability

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#276]
### Tell us about your request

We should add metrics to our internal cluster-state tracking mechanism so that we get more observability when there is drift between the internal cluster state and the actual cluster state. Some proposed metrics:

1. `karpenter_cluster_state_nodes_total`
2. `karpenter_cluster_state_pods_total` (by namespace)
3. `karpenter_cluster_state_synced`

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

No metrics for our cluster state currently.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Still need to do `karpenter_cluster_state_pods_total`
