### ISSUE TITLE
Correctly handle topology error in scheduling code

### ISSUE THREAD

**Issue by ellistarn** [kubernetes-sigs/karpenter#282]
### Tell us about your request

This error isn't being handled correctly, which can cause topology math failures: https://github.com/aws/karpenter-core/blob/main/pkg/controllers/provisioning/scheduling/scheduler.go#L122

We could precompute namespace lists in clusterstate, to avoid this being errorable at this point in the code.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

.

### Are you currently working around this issue?

.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you show an example error log and scenario where this happened?
