### ISSUE TITLE
Inject the `events.Recorder` into the `context.Context`

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#304]
### Tell us about your request

It would be nice if we didn't have to pass the event recorder through every time that we wanted to use it in any of the standard contexts. Instead, we could do something like `recorder.FromContext(ctx).Publish()`

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

Passing the event recorder around through functions anytime that it's needed

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by neverbeenthisweeb** [comment]
@jonathan-innis Do we already have the implementation for injecting `events.Recorder` into `context.Context`?

I've tried to search this repo with keyword of `.WithValue(`. However, I haven't found the mentioned implementation.

What I found are injection of setting, option, config, and controller.

Example for `settings.Settings` injection in [settings.go#L100](https://github.com/aws/karpenter-core/blob/main/pkg/apis/settings/settings.go#L100.):

```go
func ToContext(ctx context.Context, s *Settings) context.Context {
	return context.WithValue(ctx, ContextKey, s)
}
```

**Comment by neverbeenthisweeb** [comment]
Also, related to this

> It would be nice if we didn't have to pass the event recorder through every time that we wanted to use it in any of the standard contexts.

Could you provide 1 or 2 examples related to "_...pass the event recorder through every time that we wanted to use it in any of the standard contexts._"?

Just in case I am missing something in my understanding.

**Comment by jonathan-innis** [comment]
> Do we already have the implementation for passing events.Recorder into context.Context?

No, there's no implementation right now. Ideally, we could do a very similar thing to the settings injection or config injection where we create a custom key with a struct{}, inject it into the context in the `NewOperator` call and then pull it out of the context in the controllers with `recorder.FromContext(ctx).Publish(...)`

> Could you provide 1 or 2 examples related to "...pass the event recorder through every time that we wanted to use it in any of the standard contexts."?

Sure, deprovisioning is a good example where we pass the `events.Recorder` into the [NewController](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go#L76) function, we then pass those down to [each of the individual deprovisioners](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go#L87) and then each of these deprovisioners tend to pass the recorder around through different functions like [`filterCandidates`](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/drift.go#L63).

It would be nicer, since the `recorder` is a global thing, to inject it into the context (similar to the logger) and then just dereference it from the context anytime that we need it. That way, we don't have to think about passing it through all of our constructors and function calls.

**Comment by rafiramadhana** [comment]
@jonathan-innis Considering that we have several provisioners using the `events.Recorder`, would it be ok if we break this work to smaller PRs (i.e. 1 provisioner 1 PR)?

```go
NewExpiration(clk, kubeClient, cluster, provisioner, recorder),
NewDrift(kubeClient, cluster, provisioner, recorder),
NewEmptyMachineConsolidation(clk, cluster, kubeClient, provisioner, cp, recorder),
NewMultiMachineConsolidation(clk, cluster, kubeClient, provisioner, cp, recorder),
NewSingleMachineConsolidation(clk, cluster, kubeClient, provisioner, cp, recorder),
```

https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go#L87

**Comment by tzneal** [comment]
Using the context to pass non request-scoped values like this isn't recommended. The docs [say](https://pkg.go.dev/context):

> Use context Values only for request-scoped data that transits processes and APIs, not for passing optional parameters to functions. 

Our use of it for the logger is somewhat suspect, though the logger is decorated with request specific information so it could be argued that its justified.

**Comment by jonathan-innis** [comment]
> Using the context to pass non request-scoped values like this isn't recommended

Maybe treating the recorder as a global works better? Like the logger, this should always exist in every context that it's called in, and it's a singleton across the project. It's quite onerous to pass these global constructs around when you could just call out to them more generally. 

> though the logger is decorated with request specific information

Agreed. This makes the use of it different enough. I can't really imagine a scenario where we would inject request-specific information into the recorder

**Comment by jonathan-innis** [comment]
Closing as a "wont-fix". After looking into this, it seems like the dependency ordering with the `manager.Manager` doesn't make sense for the injection mechanism here into the controller context. (e.g. We pull the `events.Recorder` from the built `manager.Manager` but the `manager.Manager` needs to have the `events.Recorder` into its baseContext in order for the injection to work properly.

There's potentially an ask for `controller-runtime` to do the injection natively. Unclear if this is something that they would go for, but I imagine that pulling the `events.Recorder` out of the controller `context.Context` (like with the logger) might be useful since event recording is so ubiquitous with controllers.
