### ISSUE TITLE
E2E Test Support for `karpenter-core`

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#309]
### Tell us about your request

Currently, Karpenter is running _all_ of its E2E tests orchestrated through the [aws/karpenter] repository. This works fine when there is a single cloudprovider but we should consider orchestrating E2E tests from karpenter-core with a "fake-ish" cloudprovider so that we can have higher confidence in changes that come in through karpenter-core before they are published in new versions for the package.

We could even use a minimal cloudprovider like `k3s` to test the E2E functionality of the core feature set inside of this package.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
cc: @njtran is this one related to your kind cluster work maybe?
