### ISSUE TITLE
Decrease CI `presubmit` test time

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#336]
### Tell us about your request

Right now, our CI test jobs to run all of our test suites take around ~18m to run to completion. This is a relatively long developer loop to ensure that everything is working properly. Previously (about a month back), our test run time was around 10m (you can see this from looking at old successful Github actions and comparing the timing).

We need to track down what is causing the increase in latency (I suspect some changes that came in with the machine changes) and try to reduce the test latency time here.

### Biggest Offenders (example log)

```console
ok  	github.com/aws/karpenter-core/pkg/controllers/state	367.922s	coverage: [no statements]
ok  	github.com/aws/karpenter-core/pkg/controllers/deprovisioning	149.470s	coverage: [no statements]
ok  	github.com/aws/karpenter-core/pkg/controllers/machine/garbagecollection	125.099s	coverage: [no statements]
ok  	github.com/aws/karpenter-core/pkg/controllers/provisioning/scheduling	334.118s	coverage: [no statements]
```

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
aws/karpenter has slowed down a lot, too: https://github.com/aws/karpenter/actions.

**Comment by jonathan-innis** [comment]
I'm going to close this for now since this one is relatively old and is hard to tangibly track with exit criteria.
