### ISSUE TITLE
Unit Tests on Karpenter Pod Deletion

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/karpenter#428]
### Description

There aren't any unit tests to enforce any requirements on the Karpenter uninstall logic. This can lead us to miss things like https://github.com/aws/karpenter-core/pull/427. We should define some tests to ensure that Karpenter cleans up properly and quickly.

**Comment by Bharadwajshivam28** [comment]
Hey @jonathan-innis  I am new here and wanted to contribute and I can take on this.

**Comment by Bharadwajshivam28** [comment]
I need some details and steps to get started
