### ISSUE TITLE
Supporting Kubernetes Scheduler Config

### ISSUE THREAD

**Issue by garvinp-stripe** [kubernetes-sigs/karpenter#429]
### Description

**What problem are you trying to solve?**
At the moment, Karpenter only considers Pod Spec topology constraints however in Kubernetes it is also possible to specify constraints via https://kubernetes.io/docs/reference/scheduling/config/.

When the constraint is specified in the Scheduler Configuration and not pod spec, a pod that enters a Pending state waiting for a node that satisfy the scheduling constraint but doesn't receive an appropriate node because Karpenter doesn't consider Kubernetes Scheduling Constraint.
 
Ideally Karpenter will also understand the Scheduler constraint so any pods that needed to satisfy some scheduler constraint can get an appropriate node from Karpenter
 
**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
One way I can see this working, and that fits Kubernetes architecture, is with an API that lets a tool like Karpenter create or dry-run some kind of node placeholder, and then have the scheduler(s) in the cluster update the `status` of that NodePlaceholder to indicate which Pods might get bound there if it were real.

_Possibly_ someone could reuse (extent) [PodSchedulingContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2/) to allow `proposedNodeSpecifications` (a field I just made up) as well as the existing `potentialNodes` field.

**Comment by garvinp-stripe** [comment]
Happy to close this. I think at this time there is a need for pod scheduling constraints on the pod spec being different than cluster level scheduler config because the its possible that we want node scale out to be different that how scheduler places the pods.

**Comment by garvinp-stripe** [comment]
Happy to close this. I think at this time there is a need for pod scheduling constraints on the pod spec being different than cluster level scheduler config because the its possible that we want node scale out to be different that how scheduler places the pods.
