### ISSUE TITLE
Mega Issue: Repo Lifecycle Improvements

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/karpenter#440]
### Description

**What problem are you trying to solve?**
K8s repositories have established guidelines and use automated workflows to help maintain the repo. Karpenter should begin to adopt some of these practices to more closely align with how CNCF repositories are setup.

- [ ] Create a separate docs repository that the website is vended from
- [x] Establish guidelines for users and defined roles (path to maintainership, path to reviewer)
- [x] Bots to handle approve/merge/blocked/stale workflows automatically
- [ ] Tidy up website to abide by [website guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by akestner** [comment]
@njtran How many of these are strictly required vs. preferable?

**Comment by njtran** [comment]
Generally, I wouldn't say that any of these are required right now. This is a living list of items that I anticipate will be changed  a bit over time, especially as we figure out what is important or not. At the moment, I'd consider this a list of good-to-haves for maintaining the repo.
