### ISSUE TITLE
Support PodRequests calculations for `initContainers` with `restartPolicy: Always`

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#479]
### Description

**What problem are you trying to solve?**

Kubernetes 1.28 [introduces the `SidecarContainers` feature into alpha](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=1.28-,SidecarContainers,-false). This feature means that sidecar containers can now be ordered, meaning that upstream K8s have essentially collapsed the concept of a sidecar container down into an ordered init container with a `restartPolicy` set to `Always`. This change means that we now have to consider initContainers in our calculation of pod resource requests differently if they have a `restartPolicy` set to `Always` (since this means that the resource requests will always be utilized for all containers on the pod to run).

The changes the calculation from:
```
podRequests = max(max(each initContainers[i]),sum(containers))
```
to:
```
initContainerRequests[i] = sum(sidecar containers with index < i) + initContainers[i]
podRequests = max(max(each initContainers[i]) , sum(sidecarContainers) + sum(containers))
```

**Relevant Links**

Upstream Resource Request Calculation Code: https://github.com/kubernetes/kubernetes/blob/e2afa175e4077d767745246662170acd86affeaf/pkg/api/v1/resource/helpers.go#L96
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md 
Blog: https://www.mirantis.com/blog/understanding-kubernetes-new-sidecar-container-feature

**How important is this feature to you?**

This is a supported feature in upstream that is currently in `Alpha` but has sufficient momentum that there is belief in the community that it will be quickly pushed to `Beta`, where Karpenter will want to support it.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sadath-12** [comment]
Happy to help with this issue . Assign me
