### ISSUE TITLE
Resolve Instance Types into the NodePool Status

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#611]
### Description

**What problem are you trying to solve?**

Right now, we resolve InstanceTypes on a per-NodePool basis. This is done by making calls out to the `GetInstanceTypes()` API and then layering NodePool requirements on top of these retrieved InstanceTypes to store details about which InstanceTypes are supported for a given NodePool. This is further layered to consider the pod workload requirements and offering availability during scheduling.

We'd like to be able to store all available instance types that were resolved from the NodePool requirements into the NodePool status for observability. This would help users who don't know how diverse or constrained they are being from instance types get a better undrestanding.

It might look something like this

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
spec:
...
status:
  instanceTypes:
  - instance-type-a
  - instance-type-b
  - instance-type-c
```

We _probably_ don't want to store offering details into the status since that might get too noisy and difficult to reason about.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sadath-12** [comment]
Assign me
