### ISSUE TITLE
Unable to install v0.32.0 (karpenter.sh/v1alpha5 api service missing)

### ISSUE THREAD

**Issue by nicon89** [kubernetes-sigs/karpenter#659]
### Description

**Observed Behavior**:
Pod is not starting due to missing api service (v1alpha5):
```
$ k logs -f karpenter-7bfffc9bd6-2nllq
{"level":"DEBUG","time":"2023-10-31T13:14:04.193Z","logger":"controller","message":"loaded log configuration from file \"/etc/karpenter/logging/zap-logger-config\"","commit":"3a61217"}
{"level":"DEBUG","time":"2023-10-31T13:14:04.194Z","logger":"controller","message":"discovered karpenter version","commit":"3a61217","version":"v0.32.0"}
panic: failed to setup machine provider id indexer: failed to get API group resources: unable to retrieve the complete list of server APIs: karpenter.sh/v1alpha5: the server could not find the requested resource

goroutine 1 [running]:
github.com/samber/lo.must({0x25adc00, 0xc00017bf40}, {0xc000997730, 0x1, 0x1})
        github.com/samber/lo@v1.38.1/errors.go:51 +0x1c5
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
        github.com/aws/karpenter-core@v0.32.0/pkg/operator/operator.go:182 +0x16ce
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:33 +0x25
```

I found that the version that is installed is v1beta1:
```
$ k get apiservices.apiregistration.k8s.io |grep karpenter
v1beta1.karpenter.k8s.aws              Local     True        15s
v1beta1.karpenter.sh                   Local     True        15s
```

**Expected Behavior**:
It should work. Right now pod is in the crashloop.

**Reproduction Steps** (Please include YAML):
```
helm upgrade --install karpenter ./karpenter --namespace karpenter  --set settings.clusterName=${CLUSTER_NAME}     --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}"     --set controller.resources.requests.cpu=1     --set controller.resources.requests.memory=1Gi     --set controller.resources.limits.cpu=1     --set controller.resources.limits.memory=1Gi
```

**Versions**:
- Chart Version: v0.32.0
- Kubernetes Version (`kubectl version`): v1.24.17-eks-f8587cb

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nicon89** [comment]
I have just one version (v1beta1). I installed it using helm. Is helm release broken?

**Comment by imishchuk-carbon** [comment]
Hello, folks.

I was upgrading karpenter in two of our clusters v0.30.0 -> v0.31.2 -> v0.32.1. First upgrade went smoothly. In second cluster, though, I was getting similar error but it was about `v1beta1.karpenter.sh`.

I was able to fix this by manually upgrading CRDs, as described [here](https://karpenter.sh/v0.32/upgrading/upgrade-guide/#crd-upgrades).

```
helm upgrade --install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version v0.32.1 --namespace karpenter
```

Can this behavior be related to following note in the docs?

```
As part of the helm chart [karpenter](https://gallery.ecr.aws/karpenter/karpenter) - [source](https://github.com/aws/karpenter/blob/main/charts/karpenter/crds). Helm [does not manage the lifecycle of CRDs using this method](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/), the tool will only install the CRD during the first installation of the helm chart. Subsequent chart upgrades will not add or remove CRDs, even if the CRDs have changed. When CRDs are changed, we will make a note in the version’s upgrade guide.
```

**Comment by samuel-esp** [comment]
It seems the same problem I encountered today. I currently solved installing the v0.31 CRDs (aws-node-templates, provisioners, machines) and then doing a rollout restart deploy/karpenter

as mentioned here #792

**Comment by jonathan-innis** [comment]
> Is helm release broken

The default install of the helm chart should install both the alpha version and the beta version. My assumption is that you might run into issues with the helm install and it upgrading aspects of the CRD install if you don't go through the manual install process or use the `karpenter-crd` helm chart as described in the upgrade guide: https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades

**Comment by nicon89** [comment]
When I creates this issue I did a fresh install of Karpenter 0.32.0 for test reasons. I had to uninstall it and install version previous version, which worked well.

**Comment by ronkorland** [comment]
I had the same issue when I installed version v0.32.1
To solve the issue, I need to install all the CDRs manually from here: https://github.com/aws/karpenter/tree/main/pkg/apis/crds

BTW: the doc on how to upgrade from auto-scaler is not updated to the latest version
: https://karpenter.sh/docs/getting-started/migrating-from-cas/#set-node-affinity
This part does not exist anymore inside the Helm template

**Comment by jonathan-innis** [comment]
Closing since it looks like the original issue around CRD install was resolved.
