### ISSUE TITLE
NodePool with on_demand capacity type value quietly fails (rather than on-demand)

### ISSUE THREAD

**Issue by blame19** [kubernetes-sigs/karpenter#661]
### Description

**What problem are you trying to solve?**

I was debugging my Karpenter config. Suddenly, AWS had no longer spot instances available for a given provisioner kind, but Karpenter wasn't able to create on-demand instances. 

Karpenter (v0.27.3) logs reported:
```
ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "one", no instance type satisfied resources ... and requirements.... karpenter.sh/capacity-type In [on_demand, spot] ...; incompatible with provisioner "two", no instance type satisfied ... incompatible with provisioner "three", did not tolerate ....
```

After debugging, I discovered I had a typo in my provisioner - namely, `capacity_type = ["on_demand","spot"]` instead of the correct notation  `capacity_type = ["on-demand","spot"]`

So - the lack of nodes was due to a misconfiguration my side, but I find that the wording on the error message could be better. "No instance type satisfied" implies that the single pieces of the provisioner configuration are correct. In this case, Karpenter could already detect an incorrect value and report a provisioner configuration - especially in the case of capacity_type, that currently supports only two possible values.

**How important is this feature to you?**

Not urgent, but I would like to see more talklative logs for future versions.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by blame19** [comment]
@njtran I tested recently with 0.30, I see some minor improvements.

`Could not schedule pod, incompatible with provisioner "one", daemonset overhead={"cpu":"300m","memory":"360Mi","pods":"8"}, no instance type satisfied resources {...and requirements ..., karpenter.sh/capacity-type In [on_demand], (no instance type met the scheduling requirements or had a required offering)`

While the extra sentence points at something being wrong,  "no instance type met the scheduling requirements or had a required offering" does not indicate a misconfiguration or what exactly is failing.

**Comment by njtran** [comment]
Ah gotcha. I edited the issue title to be more reflective of the concern. Let me see if I can make this better.
