### ISSUE TITLE
Support `kubeletConfiguration.featureGates` in `Provisioner` spec

### ISSUE THREAD

**Issue by OrBin** [kubernetes-sigs/karpenter#662]
### Description

**What problem are you trying to solve?** Set feature gates for a kubelet.

**How important is this feature to you?** It's necessary for us to be able to use swap memory on Karpenter-controlled nodes when using kubelet version 1.27 or lower.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alec-w** [comment]
I think this is a separate item to the feature gates for the Karpenter APIs. This is about being able to pass `featureGates` through to the kubelet to enable feature gates for a set of nodes.

In our case we wanted to enable the feature gate `MinDomainsInPodTopologySpread` and so had node pool config
```
spec:
  template:
    spec:
      kubelet:
        featureGates:
          MinDomainsInPodTopologySpread: true
```
but got error when applying this
`strict decoding error: unknown field "spec.template.spec.kubelet.featureGates"`

Our attempt was based on https://karpenter.sh/preview/concepts/nodepools/#spectemplatespeckubelet, kubelet configuration API reference https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration and available feature gates https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Server version: v1.25.15-eks-4f4795d
Client version: v1.25.15
kubeletVersion: v1.25.15-eks-e71965b

Although I see that the kubelet configuration (and therefore featureGates) doesn't exist under the v1 reference https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/ - so could it be that this is supported by Karpenter but not the kubelet version we're using?

**Comment by jonathan-innis** [comment]
I'm closing this one as Not Planned since I don't think there is any plan among CloudProviders to surface this set of arguments generally. If you are interested in adding more feedback for AWS, here's the larger GH issue: https://github.com/aws/karpenter-provider-aws/issues/5833
