### ISSUE TITLE
Pod `do-not-consolidate` annotation to allow Nodes to be replaced for reasons other than consolidation

### ISSUE THREAD

**Issue by si-c613** [kubernetes-sigs/karpenter#672]
### Description

**What problem are you trying to solve?**

We have some workloads in our cluster where disruption is OK, but less desirable. Things like CoreDNS, Ingress, Prometheus scrapers. Karpenter allows our clusters to be highly elastic and mixed with our HPAs Karpenter is often replacing Nodes as part of consolidation. 

It is desirable that these workloads are left alone during consolidation but the Node is replaced for other interruptions such as TTL expiry or drift detection.

Currently we can add the annotation `karpenter.sh/do-not-evict: "true"` to stop these being evicted, however it is my understanding that this would block the Nodes from being replaced entirely and could lead to these being the only Pods running on the Node.

Nodes have the `karpenter.sh/do-not-consolidate: "true"` annotation, I wonder if there could be a way to apply a similar annotation to Pods to allow them to be evicted for drift/expiry but not for consolidation.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
> It feels a bit like with maintenance windows we'd either be in the same place regarding consolidation or still blocking the maintenance.

I am designing a way to add per method controls to the disruption budgets that may solve this problem. You can specify the actions you tolerate disruption for and the actions you dont on a given nodepool.

**Comment by si-c613** [comment]
@Bryce-Soghigian that looks like it should cover our use-case. Thank you.
