### ISSUE TITLE
Supporting Kubelet Config file for bootstrapping

### ISSUE THREAD

**Issue by garvinp-stripe** [kubernetes-sigs/karpenter#681]
### Description

**What problem are you trying to solve?**
Currently all AMI family, minus custom, expects /etc/eks/bootstrap.sh on the AMI. Is there anyway to open it up in the future for specifying other ways for passing taint, labels and kubelet configurations down to the userdata?
Kubelet configuration, which is already used to pass kubelet configuration information around for UserData generation within Karpenter (https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/resolver.go#L77) and is supported already by eks bootstrap script. 

With Karpenter already able to merge user data for most ami families, it should be able to open up what AMI users can use. One thing that may need to change is the ordering of merging UserData. I believe if Karpenter is able to generate kubelet config then I believe the customer's user data likely need to go after Karpenters for custom AMIs, https://github.com/aws/karpenter/blob/main/pkg/providers/amifamily/bootstrap/eksbootstrap.go#L45, since the customer user data may be the one launch kubelet. I also think labels specifically isn't passed through kubelet-config so that either needs to be dropped or pass through via env var which the customer's userdata then can use to launch kubelet.

**How important is this feature to you?**
Currently we are stuck with using custom ami family which meant all provisioner configurations are not usable. This will greatly help us get closer to using all of Karpenter's features

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by garvinp-stripe** [comment]
I think this issue should be in karpenter-provider-aws

**Comment by jonathan-innis** [comment]
> can you move this back to Karpenter-provider-aws

Yeah, it looks like this was erroneously moved and now we are kinda stuck with it over here. There's unfortunately no way to move issues between organizations and now that we are in `kubernetes-sigs`, we can't move it back. I'm fine to keep this over here right now since the history of it is so long and I'd like to not lose the context.

**Comment by jonathan-innis** [comment]
Realistically, someone should just probably pick up where https://github.com/aws/karpenter-provider-aws/pull/4504 left off since it staled out.

**Comment by garvinp-stripe** [comment]
No worries I am fine with keeping it here.

**Comment by jonathan-innis** [comment]
@garvinp-stripe With https://github.com/aws/karpenter-provider-aws/issues/5833 and https://github.com/aws/karpenter-provider-aws/issues/5134, do you think that you still need this issue open?

**Comment by garvinp-stripe** [comment]
I think that should work we can close this

**Comment by garvinp-stripe** [comment]
Closing against the two issues @jonathan-innis mentioned
