### ISSUE TITLE
Add root-dir to kubeletExtraArgs

### ISSUE THREAD

**Issue by gonfva** [kubernetes-sigs/karpenter#682]
### Description

**What problem are you trying to solve?**

kubelet allows to pass a lot of extra parameters, using the kubeletExtraArgs. In particular there is one arg called root-dir that allows to specify the directory that kubelet uses for volumes and other stuff https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#:~:text=root%2ddir

**How important is this feature to you?**

Linux can probably be bypassed, but we use a special disk (ephemeral instance) for Windows and we need to point kubelet to it.

I've looked at the code and it doesn't seem hugely difficult to modify it for our personal use case. But obviously kubeletExtraArgs has a lot of possibilities ( i.e. another example https://github.com/aws/karpenter-core/issues/683 ) and it would be good to know what's the planned approach for this.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Closing this one for AWS in favor of https://github.com/aws/karpenter-provider-aws/issues/5833
