### ISSUE TITLE
Add Log query features to kubelet config

### ISSUE THREAD

**Issue by rothgar** [kubernetes-sigs/karpenter#683]
### Description

**What problem are you trying to solve?**
Configuring kubelet to enable log query [feature gates](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-query).

It seems that most of the kubelet configuration settings we support are focused on resource utilization and eviction. Do we have any plans to extend that to other kubelet settings?

The kubelet settings I would like are:
* NodeLogQuery
* enableSystemLogHandler
* enableSystemLogQuery

NodeLogQuery is currently an alpha feature in 1.27 which is why I wanted to start a discussion about future plans for kubelet configuration for these types of settings. I'm assuming for alpha settings they would only be exposed in user-data but GA features might be easier to manage declaratively in the CRD

**How important is this feature to you?**
Medium important because this can be done via user-data, but it would be cleaner to have as part of the kubelet configuration.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Closing this one for AWS in favor of https://github.com/aws/karpenter-provider-aws/issues/5833
