### ISSUE TITLE
Custom Pricing Overrides for RIs, Savings Plans, and other strategies

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#693]
### Description

**What problem are you trying to solve?**

Karpenter should be able to understand custom pricing strategies by allowing users to manually override instance type/offering pricing for instance types that Karpenter chooses from. This would allow users to effectively modify the consolidation and provisioning behavior to prioritize certain instance types which they could mark as "cheaper" if they had discounts on certain instance types due to different Amazon EC2 billing strategies

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
> understand custom pricing strategies by allowing users to manually override instance type/offering pricing for instance types that Karpenter chooses from.

This seems like a stopgap at best.

I would posit that cloud providers should be responsible for understanding pricing on behalf of their customers, and not require their customers to configure things that should already be known.

Further, even if we did introduce this, I'm not sure about introducing this in karpenter-core -- it may be better suited as a provider specific feature.

**Comment by jonathan-innis** [comment]
Agreed, I don't think that this should have been transferred. Unfortunately, now that it _is_ transferred and we are in a different organization now, we just have to re-create the original issue in `aws/karpenter` and close this one. I think we can do that now and come up with something more generic to go into `kubernetes-sigs/karpenter` if we come up with a solid solution that should work generically for all cloud providers.

**Comment by omnibs** [comment]
There is another use-case for this which is not provider-specific.

Datadog charges us $21 per host per month. If 2 nodes have the same per-core price on EC2, the largest one will turn out to be cheaper:
- 2 `c6i.large` costs 124, but datadog bumps it to 166
- 1 `c6i.xlarge` costs 124, but datadog bumps it to 145

Karpenter makes us spend 14% more by not consolidating towards larger same-price instances.

Pricing overrides could be used for this purpose, by adding $X to every instance price, but it could also be a first-class concept.
