### ISSUE TITLE
Support `kubelet.cpuManagerPolicy` in NodePools

### ISSUE THREAD

**Issue by olibenni** [kubernetes-sigs/karpenter#697]
### Tell us about your request

I would like to provision some nodes with static CPU, without having a specific node template for those nodes.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Shipping a static CPU node with my provisioner.

### Are you currently working around this issue?

I have a specific node template using userData to set the cpu manager policy to static.
As supported by https://github.com/aws/karpenter/issues/2271

### Additional Context

I'd rather not maintain multiple node templates if the only difference between them is the userData.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@olibenni Are you blocked on this not being in the `spec.kubelet` today?

**Comment by Bryce-Soghigian** [comment]
Would be good to start negotiating if we can support all the values here: https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration?tabs=linux-node-pools#linux-kubelet-custom-configuration one of which is cpuManagerPolicy

**Comment by olibenni** [comment]
@jonathan-innis sorry for a super later reply.
This is not blocking me at all today. But I still believe, as @Bryce-Soghigian points out, that supporting all the kubectl values is helpful.

**Comment by jonathan-innis** [comment]
> But I still believe, as @Bryce-Soghigian points out, that supporting all the kubectl values is helpful

It's a good point. We combined the conversation for AWS here: https://github.com/aws/karpenter-provider-aws/issues/5833. We've gotten a number of requests to add non-scheduling related fields to the Kubelet Configuration and I figure that it will be good to combine all of this conversation into one place. It's on the AWS-side because there's pretty strong sentiment that we should [move the kubelet block over to the NodeClass API as part of v1](https://github.com/kubernetes-sigs/karpenter/issues/758#issuecomment-1971592904)

**Comment by Bryce-Soghigian** [comment]
Started a thread here on the AKS side: https://github.com/Azure/karpenter-provider-azure/issues/196
