### ISSUE TITLE
Drift Detection Without Deprovisioning

### ISSUE THREAD

**Issue by SapientGuardian** [kubernetes-sigs/karpenter#717]
### Tell us about your request

I would like to be able to enable drift detection and the consequent node labeling, but *disable* deprovisioning based on the label.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

My organization periodically builds new AMIs (security patches, etc.) and after testing, tags them as ready for production. Karpenter picks up the new AMI automatically, which is great. What I don't want to have happen is all of my production clusters reprovisioning their workers simultaneously when that happens. You can imagine, for instance, if there was a problem with that AMI that I'd lose my redundancy between regions at the worst possible time. I need more control over when and how that deprovisioning happens.

What I'd like to be able to do is be able to easily see (`kubectl get nodes -l`) which of my nodes if any have drifted, but handle the deprovisioning myself.

### Are you currently working around this issue?

When I know a new AMI is available I capture the current set of nodes and deprovision them with a script. This would include any nodes that hadn't actually drifted

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by awoimbee** [comment]
Hello, I have the exact same issue.
My use-case is ephemeral pods that can run for a full week, that should not be killed (they're labeled `karpenter.sh/do-not-disrupt`).
Sadly karpenter kills these pods because of drift, but it should not, even if there is a new AMI, even if the K8S version doesn;t match anymore.
