### ISSUE TITLE
"Do not evict" only for running pods

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/karpenter#723]
### Tell us about your request

We configure all of our helm hooks and other important pods with the do not evict flag. Some pods might not move to the running state because of having errors like CreateContainerError, CreateContainerConfigError or others.

Therefore we would like to have a better karpenter behaviour, only consider the do not evict flag if a given pod is in state creating or running...  

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Right now a single pod can keep a single node running for unlimited time. After some time this is very costly... Imagine having dozens of nodes in a left behind state. 

### Are you currently working around this issue?

Manually kill these pods. Which does not work if you have dozens of teams and projects running on a given cluster...

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mallow111** [comment]
hello folks, I sent out this PR to fix this, please check and help to review: https://github.com/aws/karpenter-core/pull/778
