### ISSUE TITLE
Vertical resizer for Karpenter

### ISSUE THREAD

**Issue by easildur24** [kubernetes-sigs/karpenter#733]
### Tell us about your request

My team just started using Karpenter in our clusters. One thing that was missing from the Karpenter deployment is the nanny that we used to have with Cluster Autoscaler. This is a bit inconvenient given that our clusters grow in time as more services are deployed on the clusters and we have to monitor the memory usage and manually bump up the resource requests. Do we already have something that we can use for Karpenter or is it on the roadmap?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Stated in the request.

### Are you currently working around this issue?

Manually bumping up the resources requests for now.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gnuletik** [comment]
/remove-lifecycle rotten

We are also looking for a way to scale Karpenter under heavy usage.

We have a cluster that scales from ~10 nodes to ~500 nodes and Karpenter memory grows to ~5GB of memory.

There's also VPA but I've never used it https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

Another approach that could be implemented in Karpenter is horizontal scaling with sharding (each instance of Karpenter could be responsible for some nodes / pods).
I've found a controller using a similar approach: https://kubevela.io/docs/v1.7/platform-engineers/system-operation/controller-sharding/
However, that seems like a huge work.

**Comment by sftim** [comment]
There is also https://github.com/kubernetes-sigs/cluster-proportional-autoscaler which, I think, might help.

https://github.com/kubernetes-sigs/karpenter/issues/733#issuecomment-1790110138

**Comment by gnuletik** [comment]
Hi @sftim,
It seems that `cluster-proportional-autoscaler` scales the number of replicas.
If I'm not wrong, that would be useless for Karpenter to only increase the number of replicas, as we need to scale vertically.

`vertical-pod-autoscaler` and `addon-resizer` does scale vertically (cpu & memory).

**Comment by sftim** [comment]
Sorry, I was thinking of https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler

**Comment by sftim** [comment]
As there's already a vertical autoscaler that seems to fit this use case:
/priority awaiting-more-evidence
