### ISSUE TITLE
Custom drain flow

### ISSUE THREAD

**Issue by dorsegal** [kubernetes-sigs/karpenter#740]
### Tell us about your request

Add a `rollout` flag when using drain. It will be used when consolidation and native termination handler (https://github.com/aws/karpenter/pull/2546)  will be ready.
The custom drain flow is like this:

1. Cordon the node
2. Do a rolling restart of the deployments that have pods running on the node.
3. Drain the node.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Currently when using consolidation feature or[ aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler) we can result of downtime or heavy performance degradation with the current implementation of `kubectl drain`

Current drain will terminate all workloads on a node and the scheduler will try to create those workloads on available nodes and if not any Karpenter will provision new node.
Even with PDB there is some level or degradation. 

### Are you currently working around this issue?

having a custom bash script that implements an alternative to `kubectl drain`

https://gist.github.com/juliohm1978/1f24f9259399e1e1edf092f1e2c7b089

### Additional Context

kubectl drain leads to downtime even with a PodDisruptionBudget https://github.com/kubernetes/kubernetes/issues/48307

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bharath509** [comment]
Please open this issue

**Comment by vainkop** [comment]
Would be nice to see a proper solution

**Comment by nikoul** [comment]
This issue also affects our single-replica deployments that are accessed through a service. Initially, I considered using a preStop hook, but this solution proved ineffective since it still transitions the pod to a terminating state and immediately removes it from the service endpoints.

**Comment by EvgeniGordeev** [comment]
https://github.com/kubernetes-sigs/karpenter/discussions/2532
