### ISSUE TITLE
Scheduler Conformance Tests

### ISSUE THREAD

**Issue by ellistarn** [kubernetes-sigs/karpenter#748]
**Tell us about your request**
What do you want us to build?

I would be great to verify our scheduler conformance by running upstream scheduler conformance tests.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Would also be great to have a suite to run core against. Notice we also ended up just copy pasting some of the AWS E2E Suites and changing the nodeclass to be AKSNodeclass. https://github.com/Azure/karpenter-provider-azure/tree/main/test/suites We ported over Integration, drift, nodeclaim and utilization. Running consolidation, chaos, etc is a next goal, but would be interesting to see if there is a space for the two teams to share one test matrix that can run on both providers when developing against core for some tests that work the same minus nodeclass on providers. 


This would be a major step forward  as upstream CAS has no Azure Conformance tests(We are looking to add some in near future). Would be great to make sure that for new core versions it will not cause regressions for other cloud providers. Given we do some of this testing when importing core so not sure on the priority. 


CC: @jackfrancis  who is doing gods work of adding conformance tests for azure for CAS I believe
