### ISSUE TITLE
CNCF donation? 

### ISSUE THREAD

**Issue by elsesiy** [kubernetes-sigs/karpenter#756]
Are there any plans to donate this project to the CNCF or host it in any outside organization?
Right now karpenter only supports aws, however I anticipate the community will add support for other clouds soon. Having the project under a well-known umbrella could help drive adoption.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
/close 

Closing the issue as it has been completed
