### ISSUE TITLE
Naming for `aws/karpenter` and `Azure/karpenter`

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#817]
### Description

I'd like to start a short discussion on what we should name the [`aws/karpenter`](https://github.com/aws/karpenter) and [`Azure/karpenter`](https://github.com/Azure/karpenter) repos now that we have `kubernetes-sigs/karpenter`. If they stay in their current state with their current naming, this creates a good amount of confusion; since, to the community, this looks like these repos are just forks of the upstream `kubernetes-sigs/karpenter` project.

Currently, the state of the world is that the Karpenter project is a `kubernetes-sigs` project that contains core controllers, interfaces and libraries that are intended to be used by CloudProviders who create provider implementations of the Karpenter project. Currently, Karpenter has CloudProvider implementations that are executed against by AWS and Azure and these implementations both: 1) Implement the [CloudProvider interface](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/cloudprovider/types.go#L36) defined in the [`types.go`](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/cloudprovider/types.go) file in `kubernetes-sigs/karpenter` and 2) Have a set of controllers which perform reconciliations and operations against the CloudProvider-specific NodeClass (`EC2NodeClass` for AWS and `AKSNodeClass` for Azure). 

Given there is some precedent in the community for naming "provider-based" things (CAPI, Cloud Controller Manager, etc.), I think that we should take-after these projects and set a standard for naming CloudProvider repos that implement the CloudProvider for the Karpenter project as `karpenter-provider-<cloudprovider-name>`

For the current CloudProviders, I believe that this would come out as:
1. AWS - `aws/karpenter-provider-aws`
2. Azure - `Azure/karpenter-provider-aks` or `Azure/karpenter-provider-azure`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
cc: @jackfrancis @tallaxes @Bryce-Soghigian @ellistarn

**Comment by ellistarn** [comment]
Agree with this analysis. I would add that there is no expectation that providers MUST use this naming convention. Rather, it's a recommended convention to minimize confusion for users.

**Comment by jackfrancis** [comment]
Thanks for documenting this, I'm in favor of standardizing across providers in a way that eliminates confusion. `karpenter-provider-<provider name>` sgtm.

**Comment by jonathan-innis** [comment]
`aws/karpenter` is now `aws/karpenter-provider-aws` 🎉 : https://github.com/aws/karpenter-provider-aws

**Comment by tallaxes** [comment]
We support the convention and will very likely adopt it soon; no timeline yet, though. (Need to track down some places where the current name is used.)

**Comment by tallaxes** [comment]
Update: Renamed to [`Azure/karpenter-provider-azure`](https://github.com/Azure/karpenter-provider-azure)

**Comment by jonathan-innis** [comment]
With that, I'm going to close out this issue then! Thanks everyone who was involved in the discussion! Glad to see that everything is basically formally migrated now!
