### ISSUE TITLE
Move Working Groups off of Amazon Chime

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/karpenter#835]
### Description

Working groups are hosted on Amazon Chime, where the meeting place for working groups should be somewhere more commonly used across all cloud providers, like zoom.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Seems like we [need to be a CNCF project](https://github.com/cncf/servicedesk#how-do-i-file-a-ticket-with-the-service-desk) listed in the [project-maintainers file](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) which only includes a few SIGs from Kubernetes. @dtzar do you know if there's a way to do this or if there's another way to request?

**Comment by jonathan-innis** [comment]
Discussed out-of-band with @gjtempleton. Basically, the work that is required here is to define a new mailing list for the sub-projects and then create a Zoom account for that mailing list email. Examples can be found in the links below:
- Create a new mailing list: https://github.com/kubernetes/k8s.io/pull/5519/files
- Create a new Zoom account for the mailing list: https://github.com/kubernetes/community/issues/7238#issuecomment-1628545293
