### ISSUE TITLE
Update CONTRIBUTING.md to improve Karpenter docs on the contributing process

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#838]
### Description

Currently, we have the boilerplate code that came from the upstream repo template for our [`CONTRIBUTING.md`](https://github.com/kubernetes-sigs/karpenter/blob/main/CONTRIBUTING.md) file. It would be nice if we updated this file to give more pointed information to contributors around how they can go about contributing to the project. 

For instance, if a feature has large enough scope, it's worthwhile to propose a larger design to the project, similar to an Autoscaling Enhancement Proposal (AEP). We can perhaps take some inspiration from the [Kubernetes Enhancement Proposal process](https://github.com/kubernetes/enhancements/blob/master/keps/README.md) to ensure that any time that we have a large enough feature that affects API surface, that we have a design proposal that covers use-cases, solutions, etc. alongside any code changes.

Here's a good example from the CAPI repo: https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md

We can also look at other CONTRIBUTING.md files throughout other upstream sub-projects.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by YashPimple** [comment]
Hi @jonathan-innis, I'd like to take this up.
