### ISSUE TITLE
Add NodeClass label to nodes for scheduling and observability

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#854]
### Description

**What problem are you trying to solve?**

There's currently an issue open in `aws/karpenter-provider-aws` that's requesting the addition of the `karpenter.k8s.aws/ec2nodeclass` as a well-known label that can be used for scheduling and assigned to nodes for observabillity: https://github.com/aws/karpenter-provider-aws/issues/5178. We think that this could be generalized across all cloud providers.

We currently don't enforce the `kind` or `apiVersion` of the `nodeClassRef` but as we are progressing to `v1`, I think that we should consider requiring users specify this. If we enforced that users had to specify this field, we could add this label for scheduling and node label propagation as `<group>/<kind>: <name>`

**How important is this feature to you?**

This improves observability for users as called out in: https://github.com/aws/karpenter-provider-aws/issues/5178

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
How about making it an annotation, not a label? That way, the annotation could store a JSON blob that uniquely identifies the group, kind and name of the node class.

If we want a simple string, I would use the URL path of that resource in Kubernetes' API. eg `/apis/karpenter.k8s.aws/*/ec2nodeclasses/example` or a string with an obvious derivation such as `karpenter.k8s.aws/ec2nodeclasses/example`.

Alternatively, use two labels, eg:
`karpenter.sh/node-class-api-path: /apis/karpenter.k8s.aws/v1beta1/ec2nodeclasses`
`karpenter.sh/node-class-name: example`

(which would still allow for compound selectors)
