### ISSUE TITLE
Addition of `cloudbuild.yaml` file

### ISSUE THREAD

**Issue by coder12git** [kubernetes-sigs/karpenter#868]
### Description

**What problem are you trying to solve?**
 I am currently participating in `Security Slam` where i am working on the task about *how releases are being made via CI*.  I've noticed that projects in community setups often use a cloudbuild.yaml file to kick off builds in their own Google Cloud Project, like this one: https://github.com/kubernetes-sigs/bom/blob/main/cloudbuild.yaml.

**How important is this feature to you?**
Switching to this community infrastructure method makes release management smoother and improves collaboration. 

I'd love to hear thoughts from @puerco on this – their insights will help us understand the real value of making this change.

**Comment by njtran** [comment]
Sounds interesting! Can you share examples of other community setups? I'd be interested to see how each community is incorporating `bom` into their builds.

**Comment by coder12git** [comment]
> Sounds interesting! Can you share examples of other community setups? I'd be interested to see how each community is incorporating `bom` into their builds.

This issue is created under `Kubernetes Security Slam` , for more details you can checkout this [doc](https://docs.google.com/document/d/1TLahqW6OpWQXbaVJ-SR8z-o0yLSoGKYTHxPU0PyyjXo/edit?pli=1)

**Comment by jonathan-innis** [comment]
> Switching to this community infrastructure method makes release management smoother and improves collaboration

I'm curious if there's a huge value here only because we are only releasing a library in this repo which only requires a git tag, all of which can be done out in the open. The only thing that needs to be automated through CI/CD is the release creation in GH, which can also be seen out in the open. 

From what I can tell, nothing we are doing should require additional cloud infrastructure.

**Comment by coder12git** [comment]
> > Switching to this community infrastructure method makes release management smoother and improves collaboration
> 
> I'm curious if there's a huge value here only because we are only releasing a library in this repo which only requires a git tag, all of which can be done out in the open. The only thing that needs to be automated through CI/CD is the release creation in GH, which can also be seen out in the open.
> 
> From what I can tell, nothing we are doing should require additional cloud infrastructure.

Yeah i agree, also this project doesn't build any images, so i believe there is no use of adding this file!

**Comment by ricardoapl** [comment]
Agreed, perhaps we can close this issue @coder12git ?

**Comment by jonathan-innis** [comment]
Closing this issue since it sounds like we all agree that this isn't necessary for this project.
