### ISSUE TITLE
When does Karpenter bind the pod to the node？

### ISSUE THREAD

**Issue by bibibox** [kubernetes-sigs/karpenter#890]
### Discussed in https://github.com/kubernetes-sigs/karpenter/discussions/859

<div type='discussions-op-text'>

<sup>Originally posted by **bibibox** December 12, 2023</sup>
i find this introduction about it:
`Scheduling enforcement: After determining launch capacity and scheduling constraints, Karpenter optimistically creates the Node object and binds the pod to it immediately. In contrast, Cluster Autoscaler does not bind pods to the nodes it creates. Instead, it relies on the kube-scheduler to make the same scheduling decision after the node has come online.`

but i cannot find the bind action from source code, and i find a doc which said the karpenter has removed the create node action yet: [https://github.com/aws/karpenter-provider-aws/blob/main/designs/node-ownership.md](url), so when does Karpenter bind the pod to the node now? Would it be nice to point out where this is in the source code, Thanks!</div>

**Comment by tzneal** [comment]
Karpenter no longer binds the pod to the node. This was removed many versions ago once the Karpetner scheduler got to the point it was no longer necessary.
