### ISSUE TITLE
Remove `utils/nodeclaim` and `utils/nodepool` functions

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#893]
### Description

**What problem are you trying to solve?**

There are some leftover helper functions in the repo that we should clean-up from the v1beta1 migration. Most notably, anything that has to do with metrics or `kubeClient` calls in these packages can just be directly moved up into the calling code, removing any need for the util abstraction.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Note Azure Provider has some dependencies here too: 
https://github.com/search?q=repo%3AAzure%2Fkarpenter+nodeclaimutil&type=code
https://github.com/search?q=repo%3AAzure%2Fkarpenter+nodepoolutil&type=code

**Comment by jonathan-innis** [comment]
Seems like we should still be able to pull these out as a breaking change with a minor version update. Do you see issues with the orchestration of those changes @Bryce-Soghigian?

**Comment by Bryce-Soghigian** [comment]
@jonathan-innis no it won't be an issue, just thought it may be worth mentioning.

**Comment by jonathan-innis** [comment]
> no it won't be an issue, just thought it may be worth mentioning

Yeah, good callout. I was mainly curious if you found these utils functions worthwhile? We are dropping them since it's just another layer of indirection that we have to handle. This indirection was useful while we were going through the v1beta1 migration (since the core controller logic didn't have to reason about what the underlying type was under-the-hood) but I think most of the value is gone now that we are just reasoning in terms of one type againa.

**Comment by njtran** [comment]
I personally thought it was a bit nicer from the perspective of the Get, List, and metrics calls, since each metric call had to reason about a specific label key on the node claim, which was just copied elsewhere to the functions.

**Comment by jonathan-innis** [comment]
> I personally thought it was a bit nicer from the perspective of the Get, List, and metrics calls

I don't think there was any value from the perspective of Get and List; it doesn't save you any LOC and the arguments and return parameters are the same.

From the perspective of metrics, I could see the argument here, since most of our metrics have the NodePoolLabelKey as a metric label; however, I think having this indirection caused a couple of bugs (particularly with the miss of the Drifted metric). We probably would have caught this with the base prometheus client since prometheus will `panic` if you try to pass labels to the metric that don't belong on the metric with the `With` function. This got obscured by using function arguments, so we were still passing the correct labels to the Disrupted metric, but with the wrong values (since the values were intended for the Drifted metric.
