### ISSUE TITLE
Karpenter KwoK Cloud Provider

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/karpenter#895]
### Description

**What problem are you trying to solve?**
Developers that want to make contributions to this repo must build and install with a cloud provider specific installation. This can be costly for users to develop and test their features, and may require maintainers to do that testing for them. Additionally, since this comes with Cloud Provider specific details, users contributing just to kubernetes-sigs/karpenter have to be aware of how the specific CP implementation may have decided to reason about general concepts. 

Creating a cloud provider using [KwoK nodes](https://github.com/kubernetes-sigs/kwok/tree/main/pkg) won't incur costs for users that need to test and validate their changes.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
So excited about this! This will be awesome when we get this in!

**Comment by njtran** [comment]
For those interested, added a design doc in #905 to detail some of the info I used to drive what I thought was a good set of instance types for #904.
