### ISSUE TITLE
Enable standard `kubernetes-sigs` upstream triage and staleness process

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#910]
### Description

**What problem are you trying to solve?**

We'd like to adopt the standard upstream triage process in `kubernetes-sigs/karpenter`. Ideally, we can orchestrate the following flow when an issue gets created:
1. An issue is created with a `kind/*` label. `needs-triage` is automatically added by `k8s-ci-bot` to the issue and won't be removed until the command `/triage accepted` is added to the issue.
2. An issue with `/triage accepted` indicates that a maintainer has seen the issue/feature/etc. and accepts that the issue should be given further consideration by the maintainer team. This is meant to sieve out issues that are not true bugs or need more information to classify them further.
3. We can get rid of the `StaleBot` CI job in favor of the `k8s-ci-bot` `lifecycle/stale`, `lifecycle/rotten` process that gets rid of triaged issues after `90d` + `30d` for stale -> rotten -> closed. 

From looking over [how `kubernetes-sigs/kustomize` does this](https://github.com/kubernetes-sigs/kustomize/issues/5499#issuecomment-1868514623), it looks like they enable this process through [here](https://github.com/kubernetes/test-infra/blob/32a90cb70955fa745bf79bd59aac877b368b061c/config/prow/plugins.yaml#L844) in `kubernetes/test-infra`; however, it would be good to get more insight into how we could manage this process more similar to upstream from those who are more familiar with the upstream machinery.

More details around issue triaging guidelines can be found here: https://www.kubernetes.dev/docs/guide/issue-triage/

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
cc: @sftim @jackfrancis who might have more insight.

**Comment by sftim** [comment]
SIG Testing are the folks who can provide advice on GitHub automation, even if it's for issues.

**Comment by Bryce-Soghigian** [comment]
would be good to have issues start with "kind/needs-triage" then we either 

1. accept: take immediate action next couple of weeks
2. reject: not planned, never planned
3. defer: accept its something the team will tackle, but not right away 


Also making better use of `lifecycle frozen` would be great as well. 

I also wonder if having a small meeting once a month to comb through the lifecycle stale issues, prioritize them and build the community roadmap out would be useful. I have a clear picture of the azure roadmap, im sure the aws maintainers have a clear idea of their roadmap, but the community roadmap for core is not as clear. 

Working group tells us immediate plans, but we could do better than that :)
