### ISSUE TITLE
Migrate existing knative logger to controller-runtime injected logger

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#922]
### Description

Controller runtime already gives us a lot of structured values that are injected into the logger that is used in the `Reconcile` context by default. We should consider moving over to use this logger instead of our existing `logging.FromContext` which leverages knative-style initialization but doesn't give us a lot of the values that controller runtime already gives us for free.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by fmuyassarov** [comment]
Hey @jonathan-innis 
If you don't mind I would like to help with this task.

**Comment by fmuyassarov** [comment]
> Hey @jonathan-innis If you don't mind I would like to help with this task.

I have added https://github.com/kubernetes-sigs/karpenter/pull/1050. But there are still things I need to test my changes about which I'm not sure yet how but will try to figure it out.
