### ISSUE TITLE
Migrate existing cloud provider neutral design docs from AWS Cloud Provider

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/karpenter#931]
### Description

**What problem are you trying to solve?**
Migrate existing design docs in github.com/aws/karpenter-provider-aws that are cloud provider neutral. 

**How important is this feature to you?**
It's important for users to know how to find design documents, especially in knowing how to create their own.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Suitable candidates: 
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/limits.md
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/consolidation.md
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/deprovisioning.md
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/node-ownership.md
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/termination.md 

- https://github.com/aws/karpenter-provider-aws/blob/main/designs/v1beta1-full-changelist.md this has aws references but still useful for main repo imo. 
- https://github.com/aws/karpenter-provider-aws/blob/main/designs/provisioner-priority.md(We could have weights also referenced in website under the nodepool example)

Might be worth referencing: https://github.com/aws/karpenter-provider-aws/blob/main/designs/node-upgrades.md in DisruptionControls design

Something like : https://github.com/aws/karpenter-provider-aws/blob/main/designs/metrics.md would be great to put in the website
