### ISSUE TITLE
Add reserved resources to NodePool

### ISSUE THREAD

**Issue by useradd-temp** [kubernetes-sigs/karpenter#945]
### Description

**What problem are you trying to solve?**

Many applications require high CPU usage immediately after startup (due to thread creation, library loading, etc.)

And after the initialization is done, it uses low CPU. In this case, using QOS as burstable is an effective way to use resources.

(manifest like this)
```
resources:
  requests:
     cpu: 100m
  limits:
    cpu: 1000m
```

However karpenter bin-packs based on requests, if bin-pack too tightly, pod won't work burstable because it don't have any spare resources.

If can set nodepool with virtual reserved resource space, k8s can use that space to make pod bustable.

While it may seem cost-effective to configure nodes to be as full as possible, but in this case it is not cost-effective because the high CPU at startup must be set to request.

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  reserved:
    cpu: 2000m
```
I expect that bin packing after subtracting the reserved value from the instance's specification will solve this problem.

+ added

Of course, this is not a perfect fix, as these updates only make sense at the moment of node selection and do not prevent pods from being placed in additional reserved space, but this happens without using karpenter.

(even be able to solve this problem with a well-tuned reserved resource)

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
The use case here seems reasonable but this also seems like it would be difficult to get right considering the kube-scheduler is responsible for scheduling the pods, not Karpenter. For example, if Karpenter needed to launch multiple nodes in a scale up event the kube-scheduler would more tightly bin-pack than Karpenter does. I'm wondering if taking advantage of [resizable resources](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) is the better solution here. Karpenter is not currently aware of resizable resources IIRC but this would guarantee that both Karpenter and the kube-scheduler respect the request.

**Comment by useradd-temp** [comment]
I think using `resizable resources` would solve the problem better. Thanks for the comment @jmdeal !
