### ISSUE TITLE
Overlap between `nodepool.spec.template.spec.requirements` and `nodepool.spec.template.spec.resources`

### ISSUE THREAD

**Issue by andrewhibbert** [kubernetes-sigs/karpenter#955]
### Description

**Observed Behavior**:

Essentially these both can be set to influence the instance type/size. So I'm wandering why `nodepool.spec.template.spec.resources` exists and if it can be removed. I don't see `nodepool.spec.template.spec.resources` discussed in https://karpenter.sh/docs/concepts/nodepools/ either.

**Expected Behavior**:

`nodepool.spec.template.spec.resources` does not exist or is documented

**Reproduction Steps** (Please include YAML):

N/A

**Versions**:
v0.32

**Comment by engedaam** [comment]
`spec.template.spec.resources` was unintentionally allowed to be set by users on the NodePool. Just created a PR to block that addition
