### ISSUE TITLE
karpenter support for civo cloud

### ISSUE THREAD

**Issue by Horiodino** [kubernetes-sigs/karpenter#974]
### Description

**What problem are you trying to solve?**
right now there is no karpenter support for civo , but now organizations are shifting to civo due to its reliable Kubernetes service, civo cloud is growing and i think this  is the right time to work on it .

**How important is this feature to you?**
i worked on ksctl , and now we are adding cluster auto-scaler , we are using karpenter for it , but for civo we doesnot have karpenter thats how i came up with it

**Comment by Horiodino** [comment]
i would like to work on it because i have worked with alot of clouds (like aws) from go lang and api perspective ,
and i also want to explore how karpenter works internally

**Comment by Bryce-Soghigian** [comment]
To achieve this you would have to implement the [cloudprovider](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/cloudprovider/types.go#L38) interface. 

```go
// CloudProvider interface is implemented by cloud providers to support provisioning.
type CloudProvider interface {
	// Create launches a NodeClaim with the given resource requests and requirements and returns a hydrated
	// NodeClaim back with resolved NodeClaim labels for the launched NodeClaim
	Create(context.Context, *v1beta1.NodeClaim) (*v1beta1.NodeClaim, error)
	// Delete removes a NodeClaim from the cloudprovider by its provider id
	Delete(context.Context, *v1beta1.NodeClaim) error
	// Get retrieves a NodeClaim from the cloudprovider by its provider id
	Get(context.Context, string) (*v1beta1.NodeClaim, error)
	// List retrieves all NodeClaims from the cloudprovider
	List(context.Context) ([]*v1beta1.NodeClaim, error)
	// GetInstanceTypes returns instance types supported by the cloudprovider.
	// Availability of types or zone may vary by nodepool or over time.  Regardless of
	// availability, the GetInstanceTypes method should always return all instance types,
	// even those with no offerings available.
	GetInstanceTypes(context.Context, *v1beta1.NodePool) ([]*InstanceType, error)
	// IsDrifted returns whether a NodeClaim has drifted from the provisioning requirements
	// it is tied to.
	IsDrifted(context.Context, *v1beta1.NodeClaim) (DriftReason, error)
	// Name returns the CloudProvider implementation name.
	Name() string
}
```

You can follow the existing Cloud Providers: 
These are listed in order of least developed to most, as to not overwhelm you. 
- [KWOK Cloud Neutral Example Provider](https://github.com/kubernetes-sigs/karpenter/blob/main/kwok/README.md)
- [Azure Provider](https://github.com/Azure/karpenter-provider-azure)
- [AWS Provider](https://github.com/aws/karpenter-provider-aws)

Does civo provide a sku pricing api? To tell you the price of each vm size? And is there an easy established pattern for creating and bootstrapping nodes outside of a nodepool concept? Karpenters cloud provider is responsible for creating individual nodeclaims, launching a vm for the underlying compute.

**Comment by Horiodino** [comment]
i just talked with civo and unfortunately both the things are not supported, but maybe in future

**Comment by Horiodino** [comment]
closed as its unsupported but gonna reopen when we have both things by civo api

**Comment by Horiodino** [comment]
> To achieve this you would have to implement the [cloudprovider](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/cloudprovider/types.go#L38) interface.
> 
> ```go
> // CloudProvider interface is implemented by cloud providers to support provisioning.
> type CloudProvider interface {
> 	// Create launches a NodeClaim with the given resource requests and requirements and returns a hydrated
> 	// NodeClaim back with resolved NodeClaim labels for the launched NodeClaim
> 	Create(context.Context, *v1beta1.NodeClaim) (*v1beta1.NodeClaim, error)
> 	// Delete removes a NodeClaim from the cloudprovider by its provider id
> 	Delete(context.Context, *v1beta1.NodeClaim) error
> 	// Get retrieves a NodeClaim from the cloudprovider by its provider id
> 	Get(context.Context, string) (*v1beta1.NodeClaim, error)
> 	// List retrieves all NodeClaims from the cloudprovider
> 	List(context.Context) ([]*v1beta1.NodeClaim, error)
> 	// GetInstanceTypes returns instance types supported by the cloudprovider.
> 	// Availability of types or zone may vary by nodepool or over time.  Regardless of
> 	// availability, the GetInstanceTypes method should always return all instance types,
> 	// even those with no offerings available.
> 	GetInstanceTypes(context.Context, *v1beta1.NodePool) ([]*InstanceType, error)
> 	// IsDrifted returns whether a NodeClaim has drifted from the provisioning requirements
> 	// it is tied to.
> 	IsDrifted(context.Context, *v1beta1.NodeClaim) (DriftReason, error)
> 	// Name returns the CloudProvider implementation name.
> 	Name() string
> }
> ```
> 
> You can follow the existing Cloud Providers: These are listed in order of least developed to most, as to not overwhelm you.
> 
>     * [KWOK Cloud Neutral Example Provider](https://github.com/kubernetes-sigs/karpenter/blob/main/kwok/README.md)
> 
>     * [Azure Provider](https://github.com/Azure/karpenter-provider-azure)
> 
>     * [AWS Provider](https://github.com/aws/karpenter-provider-aws)
> 
> 
> Does civo provide a sku pricing api? To tell you the price of each vm size? And is there an easy established pattern for creating and bootstrapping nodes outside of a nodepool concept? Karpenters cloud provider is responsible for creating individual nodeclaims, launching a vm for the underlying compute.

btw thanks for it im gonna look into codebase

**Comment by tzneal** [comment]
You don't really need the pricing provider to get started. There are other options (e.g. code the instance types/prices into your cloud provider or read from a ConfigMap that's part of the Helm install, etc.).  The ability to launch an instance of an arbitrary type supported by your cloud and attach it to your cluster is the key feature you need. 


There is an ugly way to work around that that I'll mention for completeness sake, but don't recommend.  If your cloud provider supports "node groups" for clusters, then you could create a node group per instance that Karpenter wants to launch and manage those with 1 replica per node group.
