### ISSUE TITLE
Karpenter is not working when a large volume of pods needs to be scheduled

### ISSUE THREAD

**Issue by chen1620** [kubernetes-sigs/karpenter#983]
### Description

**Observed Behavior**:
Karpenter is not working when a large volume of pods needs to be scheduled.
- When I updated the node affinity of more than 5000 pods (our cluster has more than 12k pods), Karpenter did nothing (no consideration, no provision). So, our cluster was stuck in scheduling, and most pods were in a `Pending` state.

```
Warning  FailedScheduling  33s                    default-scheduler  0/119 nodes are available: 1 Insufficient memory, 1 Too many pods, 1 node(s) had untolerated taint {kubernetes.io/arch: arm64}, 106 node(s) didn't match Pod's node affinity/selector, 2 node(s) had untolerated taint {node.kubernetes.io/unreachable: }, 9 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}. preemption: 0/119 nodes are available: 1 No preemption victims found for incoming pod, 118 Preemption is not helpful for scheduling..
```
In normal cases, when receiving this event, Karpenter will provision a new node, but in our case, the pods were still stuck in this event.

**Expected Behavior**:
- Karpenter should provision new nodes gradually or ASAP instead of doing nothing

**Reproduction Steps** (Please include YAML):
- Update hundreds or thousands of deployments at once 

**Versions**:
- Chart Version: `v0.32.1` (public.ecr.aws/karpenter)
- Kubernetes Version (`kubectl version`): `1.27`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gmdfalk** [comment]
Cross-linking this similar issue here: https://github.com/aws/karpenter-provider-aws/issues/5505
