### ISSUE TITLE
Node Disruption Budgets should(?) be a standalone CRD

### ISSUE THREAD

**Issue by garvinp-stripe** [kubernetes-sigs/karpenter#994]
### Description

**What problem are you trying to solve?**
Similar to pod disruption budget, I believe we may get some benefits here by separating out NDB. 
1. We can iterate on the API without causing backward incompatibility within NodePool version
2. We can associate NDB to NodePools (or NodeClaims) allowing us to be more flexible in how Budgets are handled. This imo makes it cleaner because disruption probably should be its own separate controller without relying on NodePool or NodeClaims
- IMO disruption is orthogonal to grouping of nodes and node configurations 

3. Reusability of NDB across node pools so its easier for operator to understand disruption behaviors across many node pools/ nodes and doesn't have to repeat the same config on many node pools

Tagging @Bryce-Soghigian since we chatted a bit about this and some of the ideas here are from him
**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
We had discussed this internally a bit before. The biggest proponent of why we didn't want to do this was that having a separate NDP (which would likely have a labelSelector to reference a set of nodepools or a set of nodes) could mean that a user that has access to an NDP would have access to block disruption for NodePools it may or may not have access for.

For instance, if a user is able to create an NDP, let's say it can set the label selector to be `karpenter.sh/nodepool=a,b,c`, now that user can control the behavior of any NodePool in the cluster, where there's no RBAC that can be set to control what this NDP can reference. It's pretty reasonable to say that anyone who can set a NodePool should be able to set the limits/controls on that specific node pool, but it's almost impossible to enforce a NodePool-level of separation of responsibilities once you include it this way.

**Comment by Bryce-Soghigian** [comment]
Similar to the Nodepool and provider ref concept where i can choose to link one budget to many nodepools not having to constantly redefine the configuration would be nice. You can either define one per pool or choose to define one you share across the whole cluster. Why selectors rather than ProviderRef style linking between the resources? 

I see this was discussed https://github.com/kubernetes-sigs/karpenter/blob/main/designs/disruption-controls.md#new-custom-resource. Will review the pr to see if I am missing any insight shared there.


Another thing I am interested about as well is in regards to the number of nodepool crds generally created on the cluster. With karpenter there most likely is less than a typical cluster configuration with managed nodepools on aks for example becaue I can represent GPU, Spot Etc all in one nodepool. If the nodepool pattern has shrunk on karpenter scale it may not be as important. AKS you can create up to 100 nodepools and some people do leverage that. The need for that seems to go away with karpenter? Is that a safe assumption?  That there are typically much fewer karpenter nodepools than cas autoscaled nodepools?

**Comment by garvinp-stripe** [comment]
> We had discussed this internally a bit before. The biggest proponent of why we didn't want to do this was that having a separate NDP (which would likely have a labelSelector to reference a set of nodepools or a set of nodes) could mean that a user that has access to an NDP would have access to block disruption for NodePools it may or may not have access for.

So from our point of view the current way Karpenter is implemented we actually don't trust any users to write their own NodePools or NodeClasses. We wrap it behind an interface that eventually becomes NodePools but they have limited control. The reason for this is because, at least for us, NodePool exposes too much surface for our users such as kubelet configurations that we feel it isn't safe that users can touch NodePools, even less so with NodeClasses. 

Though I agree that NDP is problematic since it isn't bound to namespaces similar to PDB but IMO pods management != node management. The personas that manages nodes are usually cluster admins whereas pods can be application owners who may never have access to node configurations. If Karpenter offered more granular controller over NodePools then I could see us allowing users to set their own "Pools" and "NDP" however I don't have any ideas how to protect rogue NDPs atm

**Comment by Bryce-Soghigian** [comment]
> NodePool exposes too much surface for our users such as kubelet configurations that we feel it isn't safe that users can touch NodePools, even less so with NodeClasses.

AKS has similar reservations around customers having free reign over kubelet configuration. We don't technically block it but we make it clear in our docs that messing with kubelet configuration is an unsupported scenario. 

CC: @tallaxes  do you think this is just temporary? Or do you think we will one day move to supporting users who mess with the kubelet configuration?

**Comment by garvinp-stripe** [comment]
> We had discussed this internally a bit before. The biggest proponent of why we didn't want to do this was that having a separate NDB (which would likely have a labelSelector to reference a set of nodepools or a set of nodes) could mean that a user that has access to an NDP would have access to block disruption for NodePools it may or may not have access for.

I think this isn't an issue with NDP being a separate entity but rather with NodePools themselves. The issue of cross contamination existing at the NodePool level because any NodePool can choose any "requirements' even when it collides with other NodePool. That means that any NodePool can effectively takeover another NodePool if it fully matches another NodePool's requirement + have a NodePool name that comes first alphabetically. (Which is another reason why we don't NodePools). 

IMO NDB shouldn't be tied to NodePools but actually to the nodes themselves. It makes the logic much simpler to understand. You could set your NDB to select on NodePool label but you also don't have to. This is partially necessarily if we want to support NDB on standalone NodeClaims for example. It also provides the flexibility of including nodes not managed by Karpenter to be included in calculating budgets.

**Comment by njtran** [comment]
> If Karpenter offered more granular controller over NodePools then I could see us allowing users to set their own "Pools" and "NDP" however in that case I don't have any ideas how to protect rogue NDPs atm

Seems like this is the biggest con about allowing this to be a separate CRD. What would be the mitigation here @garvinp-stripe?

**Comment by garvinp-stripe** [comment]
I think it's difficult for me to answer because from my point of view all NodePools and Node Disruption Budget in the current state cannot be managed separately so 1 persona, cluster operator, owns all of it. In which case I am not sure if rogue NDB is a problem since Node Pools also have the same issue with cross contamination and it is on the cluster operator get things right.

One very pre-mature solution I had is what if we reference NDB similar to NodePool -> NodeClass. This is similar to what we have now but allows NDB to have flexibility outside of NodePools and it's possible for NodeClaims to have NDBs without NodePools. I need far more time to figure out if this even make sense because right now something about this design doesn't sit right with me. 

I also question how should we treat nodes disruption that isn't Karpenter related with each NDB. For example: NDB A is used by NodePool A and B. NDB B is used by NodePool C. There is N nodes being deleted outside of Karpenter. Do both NDB subtract these nodes from their budget? I think that is the current behavior. Should we be allowed to pin these deletion against a separate budget? In which case NDB should but at the node level right?

Sorry I only have thoughts without much answer atm 😞

**Comment by njtran** [comment]
> Do both NDB subtract these nodes from their budget? I think that is the current behavior. 

We don't consider nodes that are outside of Karpenter's control towards the budget. 

> what if we reference NDB similar to NodePool -> NodeClass.

We also thought about this. One benefit of this is the deduplication and re-using that you get within your clusters. The other benefit I can think of is that users can define a NDB to apply to a shard of their cluster. This could make sense if users are thinking about sharding their clusters with NodePools, but then also want to group those NodePools (like multiple nodepools for a given team). 

A benefit of having it in-line with NodePools as opposed to refs is that you only need to get the NodePool, and not all NDBs in the cluster everytime that you want to disrupt a node.

**Comment by njtran** [comment]
Hey @garvinp-stripe, going to set this as a question, as I'm not sure this is something that'll be completed.
